# Hand-written Nix derivation for per-package pnpm CAFS store.
# Reads package data from pnpm-packages.json (generated by nix/scripts/gen-pnpm-packages.ts).
#
# Architecture:
#   1. Each npm package gets its own derivation (makePkgStore) that extracts the tarball
#      into a CAFS fragment using pnpm's @pnpm/store.cafs library.
#   2. A single merge derivation combines all fragments into one pnpm store.
#   3. pnpmConfigHook consumes the merged store for offline `pnpm install`.
#
# Per-package caching: Nix independently caches each makePkgStore derivation.
# When a single dependency updates, only that package's derivation re-runs — the
# other ~3000 are served from cache.
#
# All pnpm internal format knowledge (store version prefix, fetcher-version file,
# CAFS file layout) is encapsulated in pnpm-cafs-add.mjs via @pnpm/store.cafs.
# This Nix file is completely format-agnostic.
{
  stdenvNoCC,
  lib,
  fetchurl,
  nodejs,
}:
let
  packagesJson = builtins.fromJSON (builtins.readFile ./pnpm-packages.json);

  # Each package gets its own derivation: fetch tarball → write CAFS fragment
  # via pnpm's own @pnpm/store.cafs and @pnpm/constants libraries (bundled
  # in pnpm-cafs-add.mjs). The script writes the complete store structure
  # including version prefix and .fetcher-version — Nix doesn't need to
  # know pnpm's internal format at all.
  makePkgStore = key: pkg:
    let
      drv = fetchurl {
        url = pkg.url;
        hash = pkg.integrity;
      };
    in
    stdenvNoCC.mkDerivation {
      name = "airi-pnpm-pkg-${lib.replaceStrings [ "@" "/" ] [ "" "-" ] key}";
      nativeBuildInputs = [ nodejs ];
      buildPhase = ''
        node ${./scripts/pnpm-cafs-add.mjs} \
          "${drv}" \
          "$out" \
          "${key}" \
          "${pkg.integrity}"
      '';
      dontConfigure = true;
      dontUnpack = true;
      dontInstall = true;
      dontFixup = true;
    };

  pkgStores = lib.mapAttrs makePkgStore packagesJson.packages;

in
# Merge all per-package CAFS fragments into one complete pnpm store.
# CAFS is content-addressed: cp -rn is safe (same hash = same file, no conflicts).
#
# NOTICE: pkgStoresList is passed via passAsFile instead of being interpolated
# directly into buildPhase. With ~3000 packages each path is ~50 chars, the
# concatenated string exceeds ARG_MAX (~2 MB) when bash is invoked with all
# environment variables, causing E2BIG. passAsFile writes the content to a
# temp file and sets pkgStoresListPath, keeping the env small. Nix still
# tracks the string context (i.e. dependencies on all pkgStores) correctly.
stdenvNoCC.mkDerivation {
  name = "airi-pnpm-deps";
  passAsFile = [ "pkgStoresList" ];
  pkgStoresList = (lib.concatStringsSep "\n" (lib.attrValues pkgStores)) + "\n";
  buildPhase = ''
    while IFS= read -r store; do
      [ -z "$store" ] && continue
      cp -rn --no-preserve=mode "$store/." "$out/"
    done < "$pkgStoresListPath"
    # NOTICE: CAFS files with -exec suffix denote executable binaries (e.g. turbo, esbuild).
    # Set their permissions to 555 (r-xr-xr-x) so pnpm can execute them during install.
    find "$out" -type f -name "*-exec" -exec chmod 555 {} +
  '';
  dontConfigure = true;
  dontUnpack = true;
  dontInstall = true;
  dontFixup = true;
}
