# AUTO-GENERATED by nix/scripts/gen-pnpm-packages.ts — DO NOT EDIT
# Run: pnpm run nix:gen
{
  stdenvNoCC,
  lib,
  fetchurl,
  nodejs,
  pnpm,
}:
let
  # Use import (not callPackage) to avoid callPackage injecting `override` into
  # the attrset, which would cause lib.mapAttrs to iterate over it as a package.
  packages = import ./pnpm-packages.nix { inherit fetchurl; };

  # Each package gets its own derivation: extract tarball → write CAFS fragment.
  # This derivation is independently cached by Nix — only re-runs when its
  # tarball input changes (i.e. when that specific package is updated).
  # pkg = { drv = <fetchurl>; integrity = "sha512-..."; }
  makePkgStore = key: pkg:
    stdenvNoCC.mkDerivation {
      name = "airi-pnpm-pkg-${lib.replaceStrings [ "@" "/" ] [ "" "-" ] key}";
      nativeBuildInputs = [ nodejs ];
      buildPhase = ''
        node ${./scripts/cafs-add.mjs} \
          "${pkg.drv}" \
          "$out" \
          "${key}" \
          "${pkg.integrity}"
      '';
      dontConfigure = true;
      dontUnpack = true;
      dontInstall = true;
      dontFixup = true;
    };

  # 2990 independent store fragments — one per package
  pkgStores = lib.mapAttrs makePkgStore packages;

in
# Merge all per-package CAFS fragments into one complete pnpm store.
# CAFS is content-addressed: cp -rn is safe (same hash = same file, no conflicts).
#
# NOTICE: pkgStoresList is passed via passAsFile instead of being interpolated
# directly into buildPhase. With ~3000 packages each path is ~50 chars, the
# concatenated string exceeds ARG_MAX (~2 MB) when bash is invoked with all
# environment variables, causing E2BIG. passAsFile writes the content to a
# temp file and sets pkgStoresListPath, keeping the env small. Nix still
# tracks the string context (i.e. dependencies on all pkgStores) correctly.
#
# NOTICE: pnpm is added as a nativeBuildInput solely to detect the CAFS store
# version subdirectory (e.g. "v10") at merge build time via `pnpm store path`.
# This avoids hardcoding the version and automatically adapts when nixpkgs
# updates pnpm to a version that bumps its internal store layout. The per-package
# builds (makePkgStore) do NOT include pnpm, so their drv hashes are unaffected
# by pnpm version bumps — only this single merge derivation reruns.
# Fix: trailing newline in pkgStoresList - 2026-04-07
stdenvNoCC.mkDerivation {
  name = "airi-pnpm-deps";
  nativeBuildInputs = [ pnpm ];
  passAsFile = [ "pkgStoresList" ];
  pkgStoresList = (lib.concatStringsSep "\n" (lib.attrValues pkgStores)) + "\n";
  buildPhase = ''
    # Detect pnpm's internal CAFS version subdirectory (e.g. "v10").
    # pnpm appends this as the last segment of its store path.
    export HOME=$(mktemp -d)
    # Suppress packageManager version mismatch errors (we're not in a project dir)
    pnpm config set manage-package-manager-versions false 2>/dev/null || true
    storeVer=$(basename "$(pnpm store path 2>/dev/null)")
    # Validate: must be v<digits>; fall back to v10 if detection fails
    [[ "$storeVer" =~ ^v[0-9]+$ ]] || storeVer=v10

    mkdir -p "$out/$storeVer/files" "$out/$storeVer/index"
    while IFS= read -r store; do
      [ -z "$store" ] && continue
      if [ -d "$store/files" ]; then
        # NOTICE: --no-preserve=mode prevents cp from copying Nix store directory
        # permissions (0555, read-only) into $out. Without it, the first package
        # to create e.g. files/cd/ sets it to 0555, and subsequent packages fail
        # to write into it with "Permission denied".
        cp -rn --no-preserve=mode "$store/files/." "$out/$storeVer/files/"
      fi
      if [ -d "$store/index" ]; then
        cp -rn --no-preserve=mode "$store/index/." "$out/$storeVer/index/"
      fi
    done < "$pkgStoresListPath"
    # fetcherVersion=2 tells pnpmConfigHook the store is a raw directory (not a tarball)
    echo -n "2" > "$out/.fetcher-version"
  '';
  postInstall = ''
    # NOTICE: CAFS v10 files with -exec suffix denote executable binaries (e.g. turbo, esbuild).
    # Set their permissions to 555 (r-xr-xr-x) so pnpm can execute them during install.
    # Without this, pnpm install fails with EACCES when trying to run native binaries.
    find "$out" -type f -name "*-exec" -print0 | xargs -0 chmod 555
  '';
  dontConfigure = true;
  dontUnpack = true;
  dontInstall = true;
  dontFixup = true;
}
