/**
 * Twitter website CSS selector constants
 * Used to locate elements on the page
 */
export const SELECTORS = {
  COMPOSE: {
    EMOJI_BUTTON: '[data-testid="emojiButton"]',
    MEDIA_BUTTON: '[data-testid="imageOrGifButton"]',
    POLL_BUTTON: '[data-testid="createPollButton"]',
    SCHEDULE_BUTTON: '[data-testid="scheduleButton"]',
    TWEET_BUTTON: '[data-testid="tweetButtonInline"]',
    TWEET_INPUT: '[data-testid="tweetTextarea_0"]',
  },
  HOME: {
    TIMELINE: '[data-testid="primaryColumn"]',
    TRENDING: '[data-testid="sidebarColumn"]',
    TWEET_COMPOSER: '[data-testid="tweetButtonInline"]',
  },
  LOGIN: {
    LOGIN_BUTTON: 'div[role="button"]:has-text("Log in")',
    LOGIN_BUTTON_ALT: '[data-testid="login-submit-button"]',
    NEXT_BUTTON: 'div[role="button"]:has-text("Next")',
    NEXT_BUTTON_ALT: '[data-testid="login-next-button"]',
    PASSWORD_INPUT: 'input[type="password"]',
    USERNAME_INPUT: 'input[autocomplete="username"]',
  },
  MESSAGES: {
    CONVERSATION: '[data-testid="conversation"]',
    MESSAGE_INPUT: '[data-testid="dmComposerTextInput"]',
    SEND_BUTTON: '[data-testid="dmComposerSendButton"]',
  },
  NOTIFICATIONS: {
    FOLLOW: '[data-testid="notification"]',
    ITEM: '[data-testid="cellInnerDiv"]',
    LIKE: '[data-testid="notification"]',
    MENTION: '[data-testid="notification"]',
    RETWEET: '[data-testid="notification"]',
  },
  PROFILE: {
    AVATAR: '[data-testid="UserAvatar-Container"] img',
    BANNER: '[data-testid="UserProfileHeader_Items"] img',
    BIO: '[data-testid="UserDescription"]',
    DISPLAY_NAME: '[data-testid="UserName"] div span',
    FOLLOW_BUTTON: '[data-testid="followButton"]',
    FOLLOWERS_STAT: '[href$="/followers"]',
    FOLLOWING_STAT: '[href$="/following"]',
    JOIN_DATE: '[data-testid="UserProfileHeader_Items"] span:has-text("Joined")',
    LOCATION: '[data-testid="UserProfileHeader_Items"] span:has-text("Location")',
    STATS: '[data-testid="UserProfileStats"]',
    UNFOLLOW_BUTTON: '[data-testid="unfollowButton"]',
    USERNAME: '[data-testid="UserName"] div span:has-text("@")',
    VERIFIED_BADGE: '[data-testid="icon-verified"]',
    WEBSITE: '[data-testid="UserProfileHeader_Items"] a[href^="https"]',
  },
  SEARCH: {
    INPUT: '[data-testid="SearchBox_Search_Input"]',
    LATEST_TAB: '[role="tab"]:has-text("Latest")',
    PEOPLE_TAB: '[role="tab"]:has-text("People")',
    RESULT_TAB: '[role="tablist"] [role="presentation"]',
    SEARCH_FILTERS: '[data-testid="searchFiltersButton"]',
    TOP_TAB: '[role="tab"]:has-text("Top")',
  },
  TIMELINE: {
    AUTHOR_LINK: '[data-testid="User-Name"] a',
    AUTHOR_NAME: '[data-testid="User-Name"] a div span',
    AUTHOR_USERNAME: '[data-testid="User-Name"] a div div span',
    LIKE_BUTTON: '[data-testid="like"]',
    LIKE_COUNT: '[data-testid="like"] span span',
    MEDIA_CONTAINER: '[data-testid="tweetPhoto"]',
    REPLY_BUTTON: '[data-testid="reply"]',
    REPLY_COUNT: '[data-testid="reply"] span span',
    RETWEET_BUTTON: '[data-testid="retweet"]',
    RETWEET_COUNT: '[data-testid="retweet"] span span',
    TWEET: '[data-testid="tweet"]',
    TWEET_ID_CONTAINER: 'a[href*="/status/"]',
    TWEET_LINK: 'a[aria-label*="posted"]',
    TWEET_STATS: '[data-testid="tweet"] [role="group"]',
    TWEET_TEXT: '[data-testid="tweetText"]',
    TWEET_TIME: 'time',
    VIDEO_CONTAINER: '[data-testid="videoPlayer"]',
    VIEW_COUNT: '[data-testid="tweet"] [data-testid="app-text-transition-container"] span span',
  },
}
