[build]
base = "/"
command = "pnpm -F @proj-airi/ui-loading-screens... run build && pnpm -F @proj-airi/ui-loading-screens run play:build"
publish = "/packages/ui-loading-screens/playground/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
