[build]
base = "/"
command = "pnpm -F @proj-airi/provider-transformers... run build"
publish = "/packages/provider-transformers/playground/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
