[workspace]
members = [
  "crates/*",
  "apps/stage-tamagotchi/src-tauri"
]
resolver = "2"

[workspace.package]
version = "0.4.26-beta.1"

[workspace.dependencies]
tauri-plugin-mcp = { path = "./crates/tauri-plugin-mcp" }
