[workspace]
members = [
  "crates/*",
  "apps/stage-tamagotchi/src-tauri"
]
resolver = "2"

[workspace.package]
version = "0.6.0"

[workspace.dependencies]

[workspace.dependencies.tauri-plugin-mcp]
path = "./crates/tauri-plugin-mcp"
