version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - acubismmotion
  - Aerisita
  - airi
  - airi-vtuber
  - Attributify
  - audioworklet
  - Ayaka
  - Bitstream
  - bumpp
  - cientos
  - composables
  - crossws
  - csmmap
  - csmvector
  - cubismbreath
  - cubismdebug
  - cubismdefaultparameterid
  - cubismeyeblink
  - cubismmatrix44
  - cubismmoc
  - cubismmodelsettingjson
  - cubismmotionqueuemanager
  - cubismusermodel
  - cubismviewmatrix
  - cuteen
  - defu
  - demi
  - dotenvx
  - dtype
  - elevenlabs
  - formkit
  - gcornut
  - gltf
  - grammyjs
  - guiiai
  - hfspaceup
  - hfsup
  - hfup
  - histoire
  - hiyori
  - huggingface
  - huggingspace
  - hyoban
  - iconify
  - intlify
  - Kawaii
  - kwaa
  - libsodium
  - listhen
  - live2dcubismcore
  - live2dcubismframework
  - Llmmarker
  - logg
  - Maru
  - micvad
  - mkdist
  - moeru
  - Morioki
  - Myriam
  - Neko
  - nekomeowww
  - Neuro
  - Neuro-sama
  - nuxi
  - nuxt
  - nuxtjs
  - ofetch
  - Oneliner
  - onnx
  - onnxruntime
  - openai
  - opusscript
  - pgvector
  - picklist
  - picovoice
  - pinia
  - pixi
  - pixiv
  - pretrained
  - rehype
  - rushstack
  - Shadcn
  - shiki
  - shikijs
  - silero
  - sizecheck
  - Sniglet
  - supergroup
  - tamagotchi
  - taze
  - tresjs
  - typeschema
  - unhead
  - unocss
  - unplugin
  - valibot
  - VITE
  - vrma
  - vueuse
  - wavefile
  - webgpu
  - worklet
  - Xenova
  - xsai
ignoreWords: []
import: []
