packages:
  - packages/**
  - plugins/**
  - services/**
  - examples/**
  - docs/**
  - apps/**
  - '!**/dist/**'

catalog:
  '@capacitor/cli': ^8.0.0
  '@capacitor/core': ^8.0.0
  '@capacitor/ios': ^8.0.0
  '@capacitor/local-notifications': ^8.0.0
  '@guiiai/logg': ^1.2.11
  '@moeru/eslint-config': 0.1.0-beta.14
  '@moeru/std': 0.1.0-beta.14
  '@nekopaw/tempora': 0.4.0-alpha.1
  '@proj-airi/drizzle-duckdb-wasm': ^0.4.29
  '@types/audioworklet': ^0.0.92
  '@types/splitpanes': ^2.2.6
  '@xsai-ext/providers': ^0.4.0-beta.13
  '@xsai/embed': ^0.4.0-beta.13
  '@xsai/generate-speech': 0.4.0-beta.13
  '@xsai/generate-text': ^0.4.0-beta.13
  '@xsai/generate-transcription': ^0.4.0-beta.13
  '@xsai/model': ^0.4.0-beta.13
  '@xsai/shared': 0.4.0-beta.13
  '@xsai/shared-chat': 0.4.0-beta.13
  '@xsai/stream-text': ^0.4.0-beta.13
  '@xsai/tool': ^0.4.0-beta.13
  '@xsai/utils-chat': 0.4.0-beta.13
  builder-util-runtime: ^9.3.1
  embla-carousel-vue: ^8.6.0
  es-toolkit: 1.43.0
  injeca: ^0.1.5
  is-network-error: ^1.3.0
  nanoid: ^5.1.6
  ofetch: ^1.5.1
  posthog-js: 1.306.1
  splitpanes: ^4.0.4
  tsx: ^4.21.0
  uncrypto: ^0.1.3
  unplugin-info: 1.2.4
  vite-plugin-mkcert: ^1.17.9
  xsschema: ^0.4.0-beta.12
  zod: ^4.2.1

catalogMode: prefer

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.3.0
  vitest:
    '@vitest/browser-playwright': ^4.0.16
    '@vitest/coverage-v8': ^4.0.16
    vitest: ^4.0.16

onlyBuiltDependencies:
  - '@discordjs/opus'
  - '@ffmpeg-installer/darwin-arm64'
  - '@napi-rs/image'
  - '@parcel/watcher'
  - bufferutil
  - core-js
  - electron
  - electron-click-drag-plugin
  - electron-winstaller
  - es5-ext
  - esbuild
  - ffmpeg-static
  - less
  - msw
  - onnxruntime-node
  - protobufjs
  - sharp
  - simple-git-hooks
  - spawn-sync
  - utf-8-validate
  - vue-demi

overrides:
  array-flatten: npm:@nolyfill/array-flatten@^1.0.44
  axios: npm:feaxios@^0.0.23
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  isarray: npm:@nolyfill/isarray@^1.0.44
  safe-buffer: npm:@nolyfill/safe-buffer@^1.0.44
  safer-buffer: npm:@nolyfill/safer-buffer@^1.0.44
  side-channel: npm:@nolyfill/side-channel@^1.0.44
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@^1.0.44

patchedDependencies:
  srvx@0.9.8: patches/srvx@0.9.8.patch

shellEmulator: true
