packages:
  - packages/**
  - services/**
  - examples/**
  - docs/**
  - apps/**
  - '!**/dist/**'

catalog:
  '@xsai/shared': &xsai ^0.1.0-beta.9
  '@xsai/generate-speech': *xsai
  '@xsai/generate-text': *xsai
  '@xsai/generate-transcription': *xsai
  '@xsai/model': *xsai
  '@xsai/shared-chat': *xsai
  '@xsai/stream-text': *xsai
  '@xsai/tool': *xsai
  '@xsai/utils-chat': *xsai
  '@xsai/embed': *xsai
  '@xsai-ext/shared-providers': *xsai
  # TODO: remove deprecated package
  '@xsai/providers': ^0.1.0-beta.5
