packages:
  - packages/**
  - services/**
  - examples/**
  - docs/**
  - apps/**
  - '!**/dist/**'
catalog:
  '@xsai/generate-speech': ^0.1.0-beta.7
  '@xsai/generate-text': ^0.1.0-beta.7
  '@xsai/generate-transcription': ^0.1.0-beta.7
  '@xsai/model': ^0.1.0-beta.7
  '@xsai/providers': ^0.1.0-beta.5
  '@xsai/shared-chat': ^0.1.0-beta.7
  '@xsai/stream-text': ^0.1.0-beta.7
  '@xsai/tool': ^0.1.0-beta.7
