catalogMode: prefer

shellEmulator: true

packages:
  - packages/**
  - plugins/**
  - services/**
  - examples/**
  - docs/**
  - apps/**
  - '!**/dist/**'

overrides:
  array-flatten: npm:@nolyfill/array-flatten@^1.0.44
  axios: npm:feaxios@^0.0.23
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  isarray: npm:@nolyfill/isarray@^1.0.44
  safe-buffer: npm:@nolyfill/safe-buffer@^1.0.44
  safer-buffer: npm:@nolyfill/safer-buffer@^1.0.44
  side-channel: npm:@nolyfill/side-channel@^1.0.44
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@^1.0.44

catalog:
  '@guiiai/logg': ^1.2.11
  '@moeru/eslint-config': 0.1.0-beta.14
  '@moeru/std': 0.1.0-beta.14
  '@nekopaw/tempora': 0.4.0-alpha.1
  '@proj-airi/drizzle-duckdb-wasm': ^0.4.29
  '@types/audioworklet': ^0.0.92
  '@xsai-ext/providers-cloud': ^0.4.0-beta.12
  '@xsai-ext/providers-local': ^0.4.0-beta.12
  '@xsai-ext/shared-providers': 0.4.0-beta.5
  '@xsai/embed': ^0.4.0-beta.12
  '@xsai/generate-speech': 0.4.0-beta.5
  '@xsai/generate-text': ^0.4.0-beta.12
  '@xsai/generate-transcription': ^0.4.0-beta.12
  '@xsai/model': ^0.4.0-beta.12
  '@xsai/shared': ^0.4.0-beta.12
  '@xsai/shared-chat': ^0.4.0-beta.12
  '@xsai/stream-text': ^0.4.0-beta.12
  '@xsai/tool': ^0.4.0-beta.12
  '@xsai/utils-chat': 0.4.0-beta.5
  builder-util-runtime: ^9.3.1
  drizzle-valibot: ^0.4.2
  embla-carousel-vue: ^8.6.0
  es-toolkit: ^1.43.0
  hono: ^4.10.8
  injeca: ^0.1.5
  nanoid: ^5.1.6
  posthog-js: 1.306.1
  uncrypto: ^0.1.3
  unplugin-info: ^1.2.4
  valibot: ^1.2.0
  xsschema: ^0.4.0-beta.12

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.2.11
  vitest:
    '@vitest/browser-playwright': ^4.0.16
    '@vitest/coverage-v8': ^4.0.16
    vitest: ^4.0.16

ignoredBuiltDependencies:
  - '@prisma/client'
  - better-sqlite3

onlyBuiltDependencies:
  - '@discordjs/opus'
  - '@napi-rs/image'
  - '@ffmpeg-installer/darwin-arm64'
  - '@parcel/watcher'
  - bufferutil
  - core-js
  - electron
  - electron-click-drag-plugin
  - es5-ext
  - esbuild
  - ffmpeg-static
  - msw
  - onnxruntime-node
  - protobufjs
  - simple-git-hooks
  - spawn-sync
  - utf-8-validate
  - vue-demi
