packages:
  - packages/**
  - services/**
  - examples/**
  - docs/**
  - apps/**
  - '!**/dist/**'

catalog:
  '@moeru/std': ^0.1.0-beta.4
  '@proj-airi/drizzle-duckdb-wasm': ^0.4.28
  '@xsai-ext/providers-cloud': &xsai ^0.3.0-beta.5
  '@xsai-ext/providers-local': *xsai
  '@xsai-ext/shared-providers': *xsai
  '@xsai/embed': *xsai
  '@xsai/generate-speech': *xsai
  '@xsai/generate-text': *xsai
  '@xsai/generate-transcription': *xsai
  '@xsai/model': *xsai
  '@xsai/shared': *xsai
  '@xsai/shared-chat': *xsai
  '@xsai/stream-text': *xsai
  '@xsai/tool': *xsai
  '@xsai/utils-chat': *xsai
  xsschema: *xsai

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^6.3.21
