/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'IndexScenePage': RouteRecordInfo<
      'IndexScenePage',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/audio-record': RouteRecordInfo<
      '/devtools/audio-record',
      '/devtools/audio-record',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/background-gradient-blending': RouteRecordInfo<
      '/devtools/background-gradient-blending',
      '/devtools/background-gradient-blending',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/background-removal': RouteRecordInfo<
      '/devtools/background-removal',
      '/devtools/background-removal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/beat-sync': RouteRecordInfo<
      '/devtools/beat-sync',
      '/devtools/beat-sync',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/context-flow/': RouteRecordInfo<
      '/devtools/context-flow/',
      '/devtools/context-flow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/gesture-circle': RouteRecordInfo<
      '/devtools/gesture-circle',
      '/devtools/gesture-circle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/image': RouteRecordInfo<
      '/devtools/image',
      '/devtools/image',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/markdown-stress': RouteRecordInfo<
      '/devtools/markdown-stress',
      '/devtools/markdown-stress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/model-driver-mediapipe': RouteRecordInfo<
      '/devtools/model-driver-mediapipe',
      '/devtools/model-driver-mediapipe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/performance-playground': RouteRecordInfo<
      '/devtools/performance-playground',
      '/devtools/performance-playground',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/performance-visualizer': RouteRecordInfo<
      '/devtools/performance-visualizer',
      '/devtools/performance-visualizer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/plugin-host': RouteRecordInfo<
      '/devtools/plugin-host',
      '/devtools/plugin-host',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/polaroid': RouteRecordInfo<
      '/devtools/polaroid',
      '/devtools/polaroid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/providers-transcription-realtime-aliyun-nls': RouteRecordInfo<
      '/devtools/providers-transcription-realtime-aliyun-nls',
      '/devtools/providers-transcription-realtime-aliyun-nls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/use-magic-keys': RouteRecordInfo<
      '/devtools/use-magic-keys',
      '/devtools/use-magic-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/vibrant': RouteRecordInfo<
      '/devtools/vibrant',
      '/devtools/vibrant',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/websocket-inspector': RouteRecordInfo<
      '/devtools/websocket-inspector',
      '/devtools/websocket-inspector',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/airi-card/': RouteRecordInfo<
      '/settings/airi-card/',
      '/settings/airi-card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/characters/': RouteRecordInfo<
      '/settings/characters/',
      '/settings/characters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/connection/': RouteRecordInfo<
      '/settings/connection/',
      '/settings/connection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/connection/ConnectionSettings': RouteRecordInfo<
      '/settings/connection/ConnectionSettings',
      '/settings/connection/ConnectionSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/data/': RouteRecordInfo<
      '/settings/data/',
      '/settings/data',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/memory/': RouteRecordInfo<
      '/settings/memory/',
      '/settings/memory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/models/': RouteRecordInfo<
      '/settings/models/',
      '/settings/models',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/': RouteRecordInfo<
      '/settings/modules/',
      '/settings/modules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/beat-sync': RouteRecordInfo<
      '/settings/modules/beat-sync',
      '/settings/modules/beat-sync',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/consciousness': RouteRecordInfo<
      '/settings/modules/consciousness',
      '/settings/modules/consciousness',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/gaming-factorio': RouteRecordInfo<
      '/settings/modules/gaming-factorio',
      '/settings/modules/gaming-factorio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/gaming-minecraft': RouteRecordInfo<
      '/settings/modules/gaming-minecraft',
      '/settings/modules/gaming-minecraft',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/hearing': RouteRecordInfo<
      '/settings/modules/hearing',
      '/settings/modules/hearing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/mcp': RouteRecordInfo<
      '/settings/modules/mcp',
      '/settings/modules/mcp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/memory-long-term': RouteRecordInfo<
      '/settings/modules/memory-long-term',
      '/settings/modules/memory-long-term',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/memory-short-term': RouteRecordInfo<
      '/settings/modules/memory-short-term',
      '/settings/modules/memory-short-term',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/messaging-discord': RouteRecordInfo<
      '/settings/modules/messaging-discord',
      '/settings/modules/messaging-discord',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/messaging-qq': RouteRecordInfo<
      '/settings/modules/messaging-qq',
      '/settings/modules/messaging-qq',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/speech': RouteRecordInfo<
      '/settings/modules/speech',
      '/settings/modules/speech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/vision': RouteRecordInfo<
      '/settings/modules/vision',
      '/settings/modules/vision',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/x': RouteRecordInfo<
      '/settings/modules/x',
      '/settings/modules/x',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/': RouteRecordInfo<
      '/settings/providers/',
      '/settings/providers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/chat/[providerId]': RouteRecordInfo<
      '/settings/providers/chat/[providerId]',
      '/settings/providers/chat/:providerId',
      { providerId: ParamValue<true> },
      { providerId: ParamValue<false> },
      | never
    >,
    '/settings/providers/chat/azure-ai-foundry': RouteRecordInfo<
      '/settings/providers/chat/azure-ai-foundry',
      '/settings/providers/chat/azure-ai-foundry',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/chat/cloudflare-workers-ai': RouteRecordInfo<
      '/settings/providers/chat/cloudflare-workers-ai',
      '/settings/providers/chat/cloudflare-workers-ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/chat/lm-studio': RouteRecordInfo<
      '/settings/providers/chat/lm-studio',
      '/settings/providers/chat/lm-studio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/chat/ollama': RouteRecordInfo<
      '/settings/providers/chat/ollama',
      '/settings/providers/chat/ollama',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/alibaba-cloud-model-studio': RouteRecordInfo<
      '/settings/providers/speech/alibaba-cloud-model-studio',
      '/settings/providers/speech/alibaba-cloud-model-studio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/comet-api-speech': RouteRecordInfo<
      '/settings/providers/speech/comet-api-speech',
      '/settings/providers/speech/comet-api-speech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/deepgram-tts': RouteRecordInfo<
      '/settings/providers/speech/deepgram-tts',
      '/settings/providers/speech/deepgram-tts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/elevenlabs': RouteRecordInfo<
      '/settings/providers/speech/elevenlabs',
      '/settings/providers/speech/elevenlabs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/index-tts-vllm': RouteRecordInfo<
      '/settings/providers/speech/index-tts-vllm',
      '/settings/providers/speech/index-tts-vllm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/kokoro-local': RouteRecordInfo<
      '/settings/providers/speech/kokoro-local',
      '/settings/providers/speech/kokoro-local',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/microsoft-speech': RouteRecordInfo<
      '/settings/providers/speech/microsoft-speech',
      '/settings/providers/speech/microsoft-speech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/openai-audio-speech': RouteRecordInfo<
      '/settings/providers/speech/openai-audio-speech',
      '/settings/providers/speech/openai-audio-speech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/openai-compatible-audio-speech': RouteRecordInfo<
      '/settings/providers/speech/openai-compatible-audio-speech',
      '/settings/providers/speech/openai-compatible-audio-speech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/player2-speech': RouteRecordInfo<
      '/settings/providers/speech/player2-speech',
      '/settings/providers/speech/player2-speech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/volcengine': RouteRecordInfo<
      '/settings/providers/speech/volcengine',
      '/settings/providers/speech/volcengine',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/transcription/aliyun-nls-transcription': RouteRecordInfo<
      '/settings/providers/transcription/aliyun-nls-transcription',
      '/settings/providers/transcription/aliyun-nls-transcription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/transcription/browser-web-speech-api': RouteRecordInfo<
      '/settings/providers/transcription/browser-web-speech-api',
      '/settings/providers/transcription/browser-web-speech-api',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/transcription/comet-api-transcription': RouteRecordInfo<
      '/settings/providers/transcription/comet-api-transcription',
      '/settings/providers/transcription/comet-api-transcription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/transcription/openai-audio-transcription': RouteRecordInfo<
      '/settings/providers/transcription/openai-audio-transcription',
      '/settings/providers/transcription/openai-audio-transcription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/transcription/openai-compatible-audio-transcription': RouteRecordInfo<
      '/settings/providers/transcription/openai-compatible-audio-transcription',
      '/settings/providers/transcription/openai-compatible-audio-transcription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/scene/': RouteRecordInfo<
      '/settings/scene/',
      '/settings/scene',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/system/': RouteRecordInfo<
      '/settings/system/',
      '/settings/system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/system/color-scheme': RouteRecordInfo<
      '/settings/system/color-scheme',
      '/settings/system/color-scheme',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/system/developer': RouteRecordInfo<
      '/settings/system/developer',
      '/settings/system/developer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/system/general': RouteRecordInfo<
      '/settings/system/general',
      '/settings/system/general',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/v2/': RouteRecordInfo<
      '/v2/',
      '/v2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/v2/settings': RouteRecordInfo<
      '/v2/settings',
      '/v2/settings',
      Record<never, never>,
      Record<never, never>,
      | '/v2/settings/'
      | '/v2/settings/providers'
      | '/v2/settings/providers/'
      | '/v2/settings/providers/edit'
      | '/v2/settings/providers/edit/[providerId]/'
    >,
    '/v2/settings/': RouteRecordInfo<
      '/v2/settings/',
      '/v2/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/v2/settings/providers': RouteRecordInfo<
      '/v2/settings/providers',
      '/v2/settings/providers',
      Record<never, never>,
      Record<never, never>,
      | '/v2/settings/providers/'
      | '/v2/settings/providers/edit'
      | '/v2/settings/providers/edit/[providerId]/'
    >,
    '/v2/settings/providers/': RouteRecordInfo<
      '/v2/settings/providers/',
      '/v2/settings/providers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/v2/settings/providers/edit': RouteRecordInfo<
      '/v2/settings/providers/edit',
      '/v2/settings/providers/edit',
      Record<never, never>,
      Record<never, never>,
      | '/v2/settings/providers/edit/[providerId]/'
    >,
    '/v2/settings/providers/edit/[providerId]/': RouteRecordInfo<
      '/v2/settings/providers/edit/[providerId]/',
      '/v2/settings/providers/edit/:providerId',
      { providerId: ParamValue<true> },
      { providerId: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'IndexScenePage'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'src/pages/devtools/audio-record.vue': {
      routes:
        | '/devtools/audio-record'
      views:
        | never
    }
    'src/pages/devtools/background-gradient-blending.vue': {
      routes:
        | '/devtools/background-gradient-blending'
      views:
        | never
    }
    'src/pages/devtools/background-removal.vue': {
      routes:
        | '/devtools/background-removal'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/beat-sync.vue': {
      routes:
        | '/devtools/beat-sync'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/context-flow/index.vue': {
      routes:
        | '/devtools/context-flow/'
      views:
        | never
    }
    'src/pages/devtools/gesture-circle.vue': {
      routes:
        | '/devtools/gesture-circle'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/image.vue': {
      routes:
        | '/devtools/image'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/markdown-stress.vue': {
      routes:
        | '/devtools/markdown-stress'
      views:
        | never
    }
    'src/pages/devtools/model-driver-mediapipe.vue': {
      routes:
        | '/devtools/model-driver-mediapipe'
      views:
        | never
    }
    'src/pages/devtools/performance-playground.vue': {
      routes:
        | '/devtools/performance-playground'
      views:
        | never
    }
    'src/pages/devtools/performance-visualizer.vue': {
      routes:
        | '/devtools/performance-visualizer'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/plugin-host.vue': {
      routes:
        | '/devtools/plugin-host'
      views:
        | never
    }
    'src/pages/devtools/polaroid.vue': {
      routes:
        | '/devtools/polaroid'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/providers-transcription-realtime-aliyun-nls.vue': {
      routes:
        | '/devtools/providers-transcription-realtime-aliyun-nls'
      views:
        | never
    }
    'src/pages/devtools/use-magic-keys.vue': {
      routes:
        | '/devtools/use-magic-keys'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/vibrant.vue': {
      routes:
        | '/devtools/vibrant'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/websocket-inspector.vue': {
      routes:
        | '/devtools/websocket-inspector'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/airi-card/index.vue': {
      routes:
        | '/settings/airi-card/'
      views:
        | never
    }
    'src/pages/settings/characters/index.vue': {
      routes:
        | '/settings/characters/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/connection/index.vue': {
      routes:
        | '/settings/connection/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/connection/ConnectionSettings.vue': {
      routes:
        | '/settings/connection/ConnectionSettings'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/data/index.vue': {
      routes:
        | '/settings/data/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/memory/index.vue': {
      routes:
        | '/settings/memory/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/models/index.vue': {
      routes:
        | '/settings/models/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/index.vue': {
      routes:
        | '/settings/modules/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/beat-sync.vue': {
      routes:
        | '/settings/modules/beat-sync'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/consciousness.vue': {
      routes:
        | '/settings/modules/consciousness'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/gaming-factorio.vue': {
      routes:
        | '/settings/modules/gaming-factorio'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/gaming-minecraft.vue': {
      routes:
        | '/settings/modules/gaming-minecraft'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/hearing.vue': {
      routes:
        | '/settings/modules/hearing'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/mcp.vue': {
      routes:
        | '/settings/modules/mcp'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/memory-long-term.vue': {
      routes:
        | '/settings/modules/memory-long-term'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/memory-short-term.vue': {
      routes:
        | '/settings/modules/memory-short-term'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/messaging-discord.vue': {
      routes:
        | '/settings/modules/messaging-discord'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/messaging-qq.vue': {
      routes:
        | '/settings/modules/messaging-qq'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/speech.vue': {
      routes:
        | '/settings/modules/speech'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/vision.vue': {
      routes:
        | '/settings/modules/vision'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/x.vue': {
      routes:
        | '/settings/modules/x'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/index.vue': {
      routes:
        | '/settings/providers/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/chat/[providerId].vue': {
      routes:
        | '/settings/providers/chat/[providerId]'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/chat/azure-ai-foundry.vue': {
      routes:
        | '/settings/providers/chat/azure-ai-foundry'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/chat/cloudflare-workers-ai.vue': {
      routes:
        | '/settings/providers/chat/cloudflare-workers-ai'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/chat/lm-studio.vue': {
      routes:
        | '/settings/providers/chat/lm-studio'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/chat/ollama.vue': {
      routes:
        | '/settings/providers/chat/ollama'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/alibaba-cloud-model-studio.vue': {
      routes:
        | '/settings/providers/speech/alibaba-cloud-model-studio'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/comet-api-speech.vue': {
      routes:
        | '/settings/providers/speech/comet-api-speech'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/deepgram-tts.vue': {
      routes:
        | '/settings/providers/speech/deepgram-tts'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/elevenlabs.vue': {
      routes:
        | '/settings/providers/speech/elevenlabs'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/index-tts-vllm.vue': {
      routes:
        | '/settings/providers/speech/index-tts-vllm'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/kokoro-local.vue': {
      routes:
        | '/settings/providers/speech/kokoro-local'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/microsoft-speech.vue': {
      routes:
        | '/settings/providers/speech/microsoft-speech'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/openai-audio-speech.vue': {
      routes:
        | '/settings/providers/speech/openai-audio-speech'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/openai-compatible-audio-speech.vue': {
      routes:
        | '/settings/providers/speech/openai-compatible-audio-speech'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/player2-speech.vue': {
      routes:
        | '/settings/providers/speech/player2-speech'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/volcengine.vue': {
      routes:
        | '/settings/providers/speech/volcengine'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/transcription/aliyun-nls-transcription.vue': {
      routes:
        | '/settings/providers/transcription/aliyun-nls-transcription'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/transcription/browser-web-speech-api.vue': {
      routes:
        | '/settings/providers/transcription/browser-web-speech-api'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/transcription/comet-api-transcription.vue': {
      routes:
        | '/settings/providers/transcription/comet-api-transcription'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/transcription/openai-audio-transcription.vue': {
      routes:
        | '/settings/providers/transcription/openai-audio-transcription'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/transcription/openai-compatible-audio-transcription.vue': {
      routes:
        | '/settings/providers/transcription/openai-compatible-audio-transcription'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/scene/index.vue': {
      routes:
        | '/settings/scene/'
      views:
        | never
    }
    'src/pages/settings/system/index.vue': {
      routes:
        | '/settings/system/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/system/color-scheme.vue': {
      routes:
        | '/settings/system/color-scheme'
      views:
        | never
    }
    'src/pages/settings/system/developer.vue': {
      routes:
        | '/settings/system/developer'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/system/general.vue': {
      routes:
        | '/settings/system/general'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/v2/index.vue': {
      routes:
        | '/v2/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/v2/settings.vue': {
      routes:
        | '/v2/settings'
        | '/v2/settings/'
        | '/v2/settings/providers'
        | '/v2/settings/providers/'
        | '/v2/settings/providers/edit'
        | '/v2/settings/providers/edit/[providerId]/'
      views:
        | 'default'
    }
    '../../packages/stage-pages/src/pages/v2/settings/index.vue': {
      routes:
        | '/v2/settings/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/v2/settings/providers.vue': {
      routes:
        | '/v2/settings/providers'
        | '/v2/settings/providers/'
        | '/v2/settings/providers/edit'
        | '/v2/settings/providers/edit/[providerId]/'
      views:
        | 'default'
    }
    '../../packages/stage-pages/src/pages/v2/settings/providers/index.vue': {
      routes:
        | '/v2/settings/providers/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/v2/settings/providers/edit.vue': {
      routes:
        | '/v2/settings/providers/edit'
        | '/v2/settings/providers/edit/[providerId]/'
      views:
        | 'default'
    }
    '../../packages/stage-pages/src/pages/v2/settings/providers/edit/[providerId]/index.vue': {
      routes:
        | '/v2/settings/providers/edit/[providerId]/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
