import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

/**
 * Represents one migration entry consumed by the AIRI Drizzle migrator.
 *
 * @param MigrationEntry - Generated migration payload shape.
 */
export interface MigrationEntry {
  /** Drizzle journal index; migration execution order follows this value. */
  idx: number
  /** Millisecond timestamp copied from Drizzle's journal. */
  when: number
  /** Migration file tag without the `.sql` extension. */
  tag: string
  /** SHA-256 hex digest of the original SQL file contents. */
  hash: string
  /** SQL statements split into migrator-ready chunks. */
  sql: string[]
}

interface DrizzleJournal {
  entries: DrizzleJournalEntry[]
}

interface DrizzleJournalEntry {
  idx: number
  when: number
  tag: string
}

/**
 * Normalizes Drizzle migration SQL into individual executable statements.
 *
 * Before:
 * - "-- comment\nCREATE TABLE t (id text);\n--> statement-breakpoint\nSELECT 'a;b';"
 *
 * After:
 * - ["CREATE TABLE t (id text);", "SELECT 'a;b';"]
 */
export function splitMigrationSql(sql: string): string[] {
  const normalizedSql = sql
    .replace(/\/\*[\s\S]*?\*\//g, '')

  if (normalizedSql.includes('--> statement-breakpoint')) {
    return normalizedSql
      .split('--> statement-breakpoint')
      .map(normalizeMigrationStatement)
      .filter(Boolean)
  }

  return normalizedSql
    .replaceAll(';', ';\n')
    .split('\n')
    .map(normalizeMigrationStatement)
    .filter(Boolean)
}

/**
 * Normalizes a migration statement chunk after Drizzle breakpoint splitting.
 *
 * Before:
 * - "-- comment\nSELECT 1;"
 *
 * After:
 * - "SELECT 1;"
 */
function normalizeMigrationStatement(statement: string): string {
  return statement
    .split(/\r?\n\t?/g)
    .map(line => line.replace(/^\s*--.*$/g, ''))
    .map(line => line.trim())
    .join(' ')
    .trim()
}

/**
 * Builds migrator entries from a Drizzle migration directory.
 *
 * Use when:
 * - Packaging server migrations for `@proj-airi/server-schema`.
 * - Verifying Docker builds without relying on rolldown virtual modules.
 *
 * Expects:
 * - `migrationsDir` contains `meta/_journal.json`.
 * - Every journal tag has a sibling `<tag>.sql` file.
 *
 * Returns:
 * - Ordered migration entries compatible with `@proj-airi/drizzle-orm-browser-migrator`.
 */
export async function buildMigrationEntries(migrationsDir: string): Promise<MigrationEntry[]> {
  const journal = await readJournal(join(migrationsDir, 'meta/_journal.json'))
  const entries: MigrationEntry[] = []

  for (const { idx, when, tag } of journal.entries) {
    const sql = await readFile(join(migrationsDir, `${tag}.sql`), 'utf-8')
    entries.push({
      idx,
      when,
      tag,
      hash: createHash('sha256').update(sql, 'utf-8').digest('hex'),
      sql: splitMigrationSql(sql),
    })
  }

  return entries
}

/**
 * Converts migration entries into an import-free TypeScript source module.
 *
 * Use when:
 * - Emitting generated source before `tsdown` compiles `server-schema`.
 * - Avoiding deployment-critical virtual module transforms.
 *
 * Expects:
 * - Entries are already ordered and validated.
 *
 * Returns:
 * - A TypeScript module exporting `migrations`.
 */
export function migrationEntriesToSource(entries: MigrationEntry[]): string {
  return [
    '// This file is generated by src/migrations/generate.ts.',
    '// Do not edit by hand.',
    `export const migrations = ${JSON.stringify(entries, null, 2)}`,
    '',
  ].join('\n')
}

/**
 * Writes the generated migration source file used by the package entrypoint.
 *
 * Use when:
 * - Running the `@proj-airi/server-schema` build.
 * - Refreshing generated migration source after Drizzle files change.
 *
 * Expects:
 * - `migrationsDir` points at the server Drizzle output directory.
 * - `outFile` points inside this package's generated source directory.
 *
 * Returns:
 * - The generated entries that were written to disk.
 */
export async function writeMigrationSource(migrationsDir: string, outFile: string): Promise<MigrationEntry[]> {
  const entries = await buildMigrationEntries(migrationsDir)
  await mkdir(dirname(outFile), { recursive: true })
  await writeFile(outFile, migrationEntriesToSource(entries), 'utf-8')
  return entries
}

/**
 * Reads and minimally validates Drizzle's migration journal.
 */
async function readJournal(path: string): Promise<DrizzleJournal> {
  const journal = JSON.parse(await readFile(path, 'utf-8')) as DrizzleJournal

  if (!Array.isArray(journal.entries))
    throw new TypeError(`Invalid Drizzle journal at ${path}: entries must be an array.`)

  return journal
}
