[build]
base = "/"
command = "pnpm -F @proj-airi/vad... run build"
publish = "/apps/vad/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
