[build]
base = "/"
command = "pnpm -F @proj-airi/realtime-audio... run build"
publish = "/apps/realtime-audio/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
