[build]
base = "/"
command = "pnpm -F @proj-airi/stage-web... run build"
publish = "/apps/stage-web/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"
