[build]
publish = "apps/stage-web/dist"
command = "pnpm run packages:stub && pnpm -F @proj-airi/stage-web run build"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"
