[build]
base = "/"
command = "bun run --filter @proj-airi/stage-web build && bun run --filter @proj-airi/docs build:base && mv ./docs/.vitepress/dist ./apps/stage-web/dist/docs && cp ./apps/stage-web/dist/docs/sitemap.xml ./apps/stage-web/dist/sitemap.xml  && bun run --filter @proj-airi/stage-ui story:build && mv ./packages/stage-ui/.histoire/dist ./apps/stage-web/dist/ui"
publish = "/apps/stage-web/dist"

[build.environment]
NODE_VERSION = "24"
NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
