export const AUDIO_SAMPLE_RATE = 16000
export const AUDIO_CHANNELS = 1
export const AUDIO_CHUNK_DURATION_MS = 1000
export const AUDIO_CHUNK_SAMPLES = AUDIO_SAMPLE_RATE * (AUDIO_CHUNK_DURATION_MS / 1000)
export const AUDIO_CHUNK_BYTES = AUDIO_CHUNK_SAMPLES * 2

export const TTS_OUTPUT_SAMPLE_RATE = 24000

export const VIDEO_FPS_ACTIVE = 1
export const VIDEO_FPS_STANDBY = 0.2

export const RING_BUFFER_AUDIO_CAPACITY = 5
export const RING_BUFFER_VIDEO_CAPACITY = 5
