/**
 * Coding Tool Descriptors
 */

import type { ToolDescriptor } from './types'

export const codingDescriptors: ToolDescriptor[] = [
  {
    canonicalName: 'coding_review_workspace',
    concurrencySafe: true,
    defaultDeferred: true,
    destructive: false,
    displayName: 'Coding Review Workspace',
    kind: 'read',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Analyze the workspace state including git status, project structure, and recent changes. Provides context for code navigation and editing decisions.',
  },
  {
    canonicalName: 'coding_read_file',
    concurrencySafe: true,
    destructive: false,
    displayName: 'Coding Read File',
    kind: 'read',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Read the exact contents of a file with optional line range. Returns raw file content without line numbers so you can copy-paste exact strings for patches.',
  },
  {
    canonicalName: 'coding_search_text',
    concurrencySafe: true,
    destructive: false,
    displayName: 'Coding Search Text',
    kind: 'read',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Search for text patterns across files in the workspace. Supports glob patterns and result limits.',
  },
  {
    canonicalName: 'coding_search_symbol',
    concurrencySafe: true,
    destructive: false,
    displayName: 'Coding Search Symbol',
    kind: 'read',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Find symbol declarations (functions, classes, variables) in TypeScript/JavaScript files. Uses language service for accurate results.',
  },
  {
    canonicalName: 'coding_find_references',
    concurrencySafe: true,
    destructive: false,
    displayName: 'Coding Find References',
    kind: 'read',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Find all references to a symbol at a specific file location. Uses TypeScript language service for accurate cross-file references.',
  },
  {
    canonicalName: 'coding_select_target',
    concurrencySafe: true,
    defaultDeferred: true,
    destructive: false,
    displayName: 'Coding Select Target',
    kind: 'workflow',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Deterministically select a target file for editing based on file path, symbol name, or search query. Narrows scope for subsequent operations.',
  },
  {
    canonicalName: 'coding_plan_changes',
    concurrencySafe: true,
    defaultDeferred: true,
    destructive: false,
    displayName: 'Coding Plan Changes',
    kind: 'workflow',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Create a bounded coding plan for implementing changes. Limits scope to max 3 files to maintain focus and reduce risk.',
  },
  {
    canonicalName: 'coding_analyze_impact',
    concurrencySafe: true,
    defaultDeferred: true,
    destructive: false,
    displayName: 'Coding Analyze Impact',
    kind: 'read',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Analyze the 1-hop impact graph of a target file or symbol. Identifies files and symbols that may be affected by changes.',
  },
  {
    canonicalName: 'coding_validate_hypothesis',
    concurrencySafe: true,
    defaultDeferred: true,
    destructive: false,
    displayName: 'Coding Validate Hypothesis',
    kind: 'read',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Validate hypotheses about code behavior against the actual impact graph. Helps catch incorrect assumptions before making changes.',
  },
  {
    canonicalName: 'coding_diagnose_changes',
    concurrencySafe: true,
    defaultDeferred: true,
    destructive: false,
    displayName: 'Coding Diagnose Changes',
    kind: 'read',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Perform root cause analysis when validation or tests fail after changes. Identifies likely sources of problems.',
  },
  {
    canonicalName: 'coding_capture_validation_baseline',
    concurrencySafe: false,
    defaultDeferred: true,
    destructive: false,
    displayName: 'Coding Capture Validation Baseline',
    kind: 'read',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Capture a baseline of current diffs and optionally create a temporary worktree for safe experimentation.',
  },
  {
    canonicalName: 'coding_review_changes',
    concurrencySafe: true,
    defaultDeferred: true,
    destructive: false,
    displayName: 'Coding Review Changes',
    kind: 'read',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Perform a deterministic diff-aware review of changes in the current file. Identifies potential issues and inconsistencies.',
  },
  {
    canonicalName: 'coding_apply_patch',
    concurrencySafe: false,
    destructive: true,
    displayName: 'Coding Apply Patch',
    kind: 'write',
    lane: 'coding',
    public: true,
    readOnly: false,
    requiresApprovalByDefault: true,
    summary: 'Apply a patch to a file by replacing an old string with a new string. This is a mutating operation that modifies file contents.',
  },
  {
    canonicalName: 'coding_compress_context',
    concurrencySafe: true,
    defaultDeferred: true,
    destructive: false,
    displayName: 'Coding Compress Context',
    kind: 'workflow',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Summarize the current coding context including goals, file states, and recent results. Useful for managing context window limits.',
  },
  {
    canonicalName: 'coding_report_status',
    concurrencySafe: true,
    defaultDeferred: true,
    destructive: false,
    displayName: 'Coding Report Status',
    kind: 'workflow',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'Report structured execution status including completion state, summary, affected files, commands run, and validation checks.',
  },
  {
    canonicalName: 'coding_write_file',
    concurrencySafe: false,
    destructive: true,
    displayName: 'Coding Write File',
    kind: 'write',
    lane: 'coding',
    public: true,
    readOnly: false,
    requiresApprovalByDefault: true,
    summary: 'Create a new file or overwrite an existing file with provided content. Creates parent directories if they do not exist. For partial edits, use coding_apply_patch instead.',
  },
  {
    canonicalName: 'coding_list_files',
    concurrencySafe: true,
    destructive: false,
    displayName: 'Coding List Files',
    kind: 'read',
    lane: 'coding',
    public: true,
    readOnly: true,
    requiresApprovalByDefault: false,
    summary: 'List files and directories matching glob patterns within the workspace. Supports include/exclude patterns. Returns relative paths with file/directory indicators.',
  },

  // Autonomous coding loop
  {
    canonicalName: 'coding_agentic_run',
    concurrencySafe: false,
    defaultDeferred: true,
    destructive: true,
    displayName: 'Coding Agentic Run',
    kind: 'write',
    lane: 'coding',
    public: true,
    readOnly: false,
    requiresApprovalByDefault: true,
    summary: 'Start an autonomous coding loop to complete a task. The agent will read, search, edit files, and run commands to accomplish the given goal.',
  },
]
