/**
 * Coding Tool Descriptors
 */

import type { ToolDescriptor } from './types'

export const codingDescriptors: ToolDescriptor[] = [
  {
    canonicalName: 'coding_review_workspace',
    displayName: 'Coding Review Workspace',
    summary: 'Analyze the workspace state including git status, project structure, and recent changes. Provides context for code navigation and editing decisions.',
    lane: 'coding',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_read_file',
    displayName: 'Coding Read File',
    summary: 'Read the contents of a file with optional line range. Returns file content with line numbers for precise navigation.',
    lane: 'coding',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_search_text',
    displayName: 'Coding Search Text',
    summary: 'Search for text patterns across files in the workspace. Supports glob patterns and result limits.',
    lane: 'coding',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_search_symbol',
    displayName: 'Coding Search Symbol',
    summary: 'Find symbol declarations (functions, classes, variables) in TypeScript/JavaScript files. Uses language service for accurate results.',
    lane: 'coding',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_find_references',
    displayName: 'Coding Find References',
    summary: 'Find all references to a symbol at a specific file location. Uses TypeScript language service for accurate cross-file references.',
    lane: 'coding',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_select_target',
    displayName: 'Coding Select Target',
    summary: 'Deterministically select a target file for editing based on file path, symbol name, or search query. Narrows scope for subsequent operations.',
    lane: 'coding',
    kind: 'workflow',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_plan_changes',
    displayName: 'Coding Plan Changes',
    summary: 'Create a bounded coding plan for implementing changes. Limits scope to max 3 files to maintain focus and reduce risk.',
    lane: 'coding',
    kind: 'workflow',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_analyze_impact',
    displayName: 'Coding Analyze Impact',
    summary: 'Analyze the 1-hop impact graph of a target file or symbol. Identifies files and symbols that may be affected by changes.',
    lane: 'coding',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_validate_hypothesis',
    displayName: 'Coding Validate Hypothesis',
    summary: 'Validate hypotheses about code behavior against the actual impact graph. Helps catch incorrect assumptions before making changes.',
    lane: 'coding',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_diagnose_changes',
    displayName: 'Coding Diagnose Changes',
    summary: 'Perform root cause analysis when validation or tests fail after changes. Identifies likely sources of problems.',
    lane: 'coding',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_capture_validation_baseline',
    displayName: 'Coding Capture Validation Baseline',
    summary: 'Capture a baseline of current diffs and optionally create a temporary worktree for safe experimentation.',
    lane: 'coding',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_review_changes',
    displayName: 'Coding Review Changes',
    summary: 'Perform a deterministic diff-aware review of changes in the current file. Identifies potential issues and inconsistencies.',
    lane: 'coding',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_apply_patch',
    displayName: 'Coding Apply Patch',
    summary: 'Apply a patch to a file by replacing an old string with a new string. This is a mutating operation that modifies file contents.',
    lane: 'coding',
    kind: 'write',
    readOnly: false,
    destructive: true,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'coding_compress_context',
    displayName: 'Coding Compress Context',
    summary: 'Summarize the current coding context including goals, file states, and recent results. Useful for managing context window limits.',
    lane: 'coding',
    kind: 'workflow',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'coding_report_status',
    displayName: 'Coding Report Status',
    summary: 'Report structured execution status including completion state, summary, affected files, commands run, and validation checks.',
    lane: 'coding',
    kind: 'workflow',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
]
