/**
 * Desktop, Terminal, and Browser DOM Tool Descriptors
 *
 * These are the main computer use tools from register-tools.ts
 */

import type { ToolDescriptor } from './types'

export const desktopDescriptors: ToolDescriptor[] = [
  // Desktop observation tools
  {
    canonicalName: 'desktop_get_capabilities',
    displayName: 'Desktop Get Capabilities',
    summary: 'Get system capabilities, preflight checks, and policy configuration. Returns executor type, permissions, display info, and coordinate space details.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_observe_windows',
    displayName: 'Desktop Observe Windows',
    summary: 'List visible windows with optional app name filter. Returns window titles, bounds, and PIDs.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_screenshot',
    displayName: 'Desktop Screenshot',
    summary: 'Capture a screenshot of the current display. Returns the image in base64 format with optional metadata label.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },

  // Desktop interaction tools
  {
    canonicalName: 'desktop_open_app',
    displayName: 'Desktop Open App',
    summary: 'Open an application. Requires the app to be in COMPUTER_USE_OPENABLE_APPS configuration.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'desktop_focus_app',
    displayName: 'Desktop Focus App',
    summary: 'Focus an application window. Requires the app to be in COMPUTER_USE_OPENABLE_APPS configuration.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'desktop_click',
    displayName: 'Desktop Click',
    summary: 'Click at screen coordinates. Supports left/right/middle buttons and click count for double-click.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_type_text',
    displayName: 'Desktop Type Text',
    summary: 'Type text into the focused element. Optionally click at coordinates first. Long text (>160 chars) requires approval.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_press_keys',
    displayName: 'Desktop Press Keys',
    summary: 'Press a keyboard shortcut or key combination. Some shortcuts (Cmd+Q, Cmd+Space, etc.) are denied by policy.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_scroll',
    displayName: 'Desktop Scroll',
    summary: 'Scroll the screen at optional coordinates. Supports both vertical and horizontal scrolling.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'desktop_wait',
    displayName: 'Desktop Wait',
    summary: 'Wait for a specified duration (0-30000ms). Useful for letting UI animations complete.',
    lane: 'desktop',
    kind: 'control',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },

  // Terminal tools
  {
    canonicalName: 'terminal_exec',
    displayName: 'Terminal Exec',
    summary: 'Execute a shell command in the local terminal. Returns stdout, stderr, exit code, and timing. Always requires approval.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: true,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'terminal_reset',
    displayName: 'Terminal Reset',
    summary: 'Reset the terminal state. Clears accumulated command history and state.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },

  // Browser DOM tools (extension-based)
  {
    canonicalName: 'browser_dom_read_page',
    displayName: 'Browser DOM Read Page',
    summary: 'Read the DOM structure from all frames in the browser via the extension bridge. Returns interactive elements and page structure.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'browser_dom_find_elements',
    displayName: 'Browser DOM Find Elements',
    summary: 'Find elements in the browser DOM matching a selector or role. Returns matching elements with bounds and attributes.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },

  // Clipboard tools
  {
    canonicalName: 'clipboard_read_text',
    displayName: 'Clipboard Read Text',
    summary: 'Read text content from the system clipboard. Requires approval due to privacy sensitivity.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'clipboard_write_text',
    displayName: 'Clipboard Write Text',
    summary: 'Write text content to the system clipboard. Requires approval due to data sensitivity.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },

  // Secret/env tools
  {
    canonicalName: 'secret_read_env_value',
    displayName: 'Secret Read Env Value',
    summary: 'Read an environment variable value. Requires approval due to potential exposure of secrets.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: true,
    public: true,
  },

  // Workflow tools
  {
    canonicalName: 'workflow_begin',
    displayName: 'Workflow Begin',
    summary: 'Begin a new workflow execution with a specified goal and steps. Initializes task tracking.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'workflow_step_start',
    displayName: 'Workflow Step Start',
    summary: 'Start executing a workflow step. Transitions the workflow state machine.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'workflow_step_complete',
    displayName: 'Workflow Step Complete',
    summary: 'Mark the current workflow step as complete with an optional outcome message.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'workflow_complete',
    displayName: 'Workflow Complete',
    summary: 'Complete the current workflow with a final status and summary.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'workflow_get_state',
    displayName: 'Workflow Get State',
    summary: 'Get the current workflow execution state including active task, steps, and progress.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
]

/**
 * Internal/test tools (not exposed to MCP clients by default)
 */
export const internalDescriptors: ToolDescriptor[] = [
  {
    canonicalName: 'desktop_open_test_target',
    displayName: 'Desktop Open Test Target',
    summary: 'Open a test target for development/testing purposes. Only available when test tools are enabled.',
    lane: 'internal',
    kind: 'internal',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: false,
  },
]

/**
 * Meta/directory tools
 */
export const metaDescriptors: ToolDescriptor[] = [
  {
    canonicalName: 'tool_directory',
    displayName: 'Tool Directory',
    summary: 'List available tools with optional filtering by lane, kind, or search query. Returns a compact directory for navigation and a structured list for programmatic access.',
    lane: 'internal',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
]
