name: player-joined
version: 1

trigger:
  modality: system
  kind: player_joined

accumulator:
  threshold: 1
  window: 1s

signal:
  type: social_presence
  description: 'Player {{ displayName }} joined the server'
  confidence: 1.0
  metadata:
    event: player_joined
    playerId: '{{ playerId }}'
    displayName: '{{ displayName }}'
