name: teabag-attention
version: 1

trigger:
  modality: sighted
  kind: sneak_toggle
  where:
    entityType: player

accumulator:
  threshold: 6
  window: 1s
  mode: sliding

signal:
  type: social_gesture
  description: 'Player {{ displayName }} is teabagging (rapid sneaking)'
  confidence: 1.0
  metadata:
    gesture: teabag
    distance: '{{ distance }}'
    displayName: '{{ displayName }}'
    hasLineOfSight: '{{ hasLineOfSight }}'
