// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot'

/**
 * Item reference
 *
 * An internal identifier for an item to reference.
 */
export const vItemReferenceParam = v.object({
  type: v.nullish(v.picklist(['item_reference'])),
  id: v.string(),
})

export const vReasoningSummaryContentParam = v.object({
  type: v.optional(v.picklist(['summary_text']), 'summary_text'),
  text: v.pipe(v.string(), v.maxLength(10485760)),
})

export const vReasoningItemParam = v.object({
  id: v.nullish(v.string()),
  type: v.optional(v.picklist(['reasoning']), 'reasoning'),
  summary: v.array(vReasoningSummaryContentParam),
  content: v.optional(v.null()),
  encrypted_content: v.nullish(v.string()),
})

/**
 * Compaction item
 *
 * A compaction item generated by the [`v1/responses/compact` API](/docs/api-reference/responses/compact).
 */
export const vCompactionSummaryItemParam = v.object({
  id: v.nullish(v.string()),
  type: v.optional(v.picklist(['compaction']), 'compaction'),
  encrypted_content: v.pipe(v.string(), v.maxLength(10485760)),
})

/**
 * Input text
 *
 * A text input to the model.
 */
export const vInputTextContentParam = v.object({
  type: v.optional(v.picklist(['input_text']), 'input_text'),
  text: v.pipe(v.string(), v.maxLength(10485760)),
})

export const vImageDetail = v.picklist([
  'low',
  'high',
  'auto',
])

/**
 * Input image
 *
 * An image input to the model. Learn about [image inputs](/docs/guides/vision)
 */
export const vInputImageContentParamAutoParam = v.object({
  type: v.optional(v.picklist(['input_image']), 'input_image'),
  image_url: v.nullish(v.pipe(v.string(), v.maxLength(20971520))),
  detail: v.nullish(v.intersect([vImageDetail, v.unknown()])),
})

/**
 * Input file
 *
 * A file input to the model.
 */
export const vInputFileContentParam = v.object({
  type: v.optional(v.picklist(['input_file']), 'input_file'),
  filename: v.nullish(v.string()),
  file_data: v.nullish(v.pipe(v.string(), v.maxLength(33554432))),
  file_url: v.nullish(v.string()),
})

export const vUrlCitationParam = v.object({
  type: v.optional(v.picklist(['url_citation']), 'url_citation'),
  start_index: v.pipe(v.number(), v.integer(), v.minValue(0)),
  end_index: v.pipe(v.number(), v.integer(), v.minValue(0)),
  url: v.string(),
  title: v.string(),
})

export const vOutputTextContentParam = v.object({
  type: v.optional(v.picklist(['output_text']), 'output_text'),
  text: v.pipe(v.string(), v.maxLength(10485760)),
  annotations: v.optional(v.array(vUrlCitationParam)),
})

export const vRefusalContentParam = v.object({
  type: v.optional(v.picklist(['refusal']), 'refusal'),
  refusal: v.pipe(v.string(), v.maxLength(10485760)),
})

export const vFunctionCallStatus = v.picklist([
  'in_progress',
  'completed',
  'incomplete',
])

export const vFunctionCallItemParam = v.object({
  id: v.nullish(v.string()),
  call_id: v.pipe(v.string(), v.minLength(1), v.maxLength(64)),
  type: v.optional(v.picklist(['function_call']), 'function_call'),
  name: v.pipe(v.string(), v.minLength(1), v.maxLength(64), v.regex(/^[\w-]+$/)),
  arguments: v.string(),
  status: v.nullish(v.intersect([vFunctionCallStatus, v.unknown()])),
})

/**
 * A content block representing a video input to the model.
 */
export const vInputVideoContent = v.object({
  type: v.picklist(['input_video']),
  video_url: v.string(),
})

export const vIncludeEnum = v.picklist(['reasoning.encrypted_content', 'message.output_text.logprobs'])

export const vEmptyModelParam = v.record(v.string(), v.unknown())

export const vFunctionToolParam = v.object({
  name: v.pipe(v.string(), v.minLength(1), v.maxLength(64), v.regex(/^[\w-]+$/)),
  description: v.nullish(v.string()),
  parameters: v.nullish(vEmptyModelParam),
  strict: v.optional(v.boolean()),
  type: v.optional(v.picklist(['function']), 'function'),
})

export const vResponsesToolParam = vFunctionToolParam

export const vSpecificFunctionParam = v.object({
  type: v.optional(v.picklist(['function']), 'function'),
  name: v.string(),
})

export const vSpecificToolChoiceParam = vSpecificFunctionParam

export const vToolChoiceValueEnum = v.picklist([
  'none',
  'auto',
  'required',
])

export const vAllowedToolsParam = v.object({
  type: v.optional(v.picklist(['allowed_tools']), 'allowed_tools'),
  tools: v.pipe(v.array(vSpecificToolChoiceParam), v.minLength(1), v.maxLength(128)),
  mode: v.optional(v.intersect([vToolChoiceValueEnum, v.unknown()])),
})

/**
 * Controls which tool the model should use, if any.
 */
export const vToolChoiceParam = v.union([
  vSpecificToolChoiceParam,
  vToolChoiceValueEnum,
  vAllowedToolsParam,
])

/**
 * Set of 16 key-value pairs that can be attached to an object. This can be         useful for storing additional information about the object in a structured         format, and querying for objects via API or the dashboard.
 * Keys are strings with a maximum length of 64 characters. Values are strings         with a maximum length of 512 characters.
 */
export const vMetadataParam = v.record(v.string(), v.pipe(v.string(), v.maxLength(512)))

export const vTextResponseFormat = v.object({
  type: v.optional(v.picklist(['text']), 'text'),
})

export const vJsonSchemaResponseFormatParam = v.object({
  type: v.optional(v.picklist(['json_schema'])),
  description: v.optional(v.string()),
  name: v.optional(v.string()),
  schema: v.optional(v.record(v.string(), v.unknown())),
  strict: v.nullish(v.boolean()),
})

export const vTextFormatParam = v.union([vTextResponseFormat, vJsonSchemaResponseFormatParam])

export const vVerbosityEnum = v.picklist([
  'low',
  'medium',
  'high',
])

export const vTextParam = v.object({
  format: v.nullish(vTextFormatParam),
  verbosity: v.optional(v.intersect([vVerbosityEnum, v.unknown()])),
})

/**
 * Options that control streamed response behavior.
 */
export const vStreamOptionsParam = v.object({
  include_obfuscation: v.optional(v.boolean()),
})

export const vReasoningEffortEnum = v.picklist([
  'none',
  'low',
  'medium',
  'high',
  'xhigh',
])

export const vReasoningSummaryEnum = v.picklist([
  'concise',
  'detailed',
  'auto',
])

/**
 * **gpt-5 and o-series models only** Configuration options for [reasoning models](https://platform.openai.com/docs/guides/reasoning).
 */
export const vReasoningParam = v.object({
  effort: v.nullish(vReasoningEffortEnum),
  summary: v.nullish(v.intersect([vReasoningSummaryEnum, v.unknown()])),
})

export const vTruncationEnum = v.picklist(['auto', 'disabled'])

export const vServiceTierEnum = v.picklist([
  'auto',
  'default',
  'flex',
  'priority',
])

/**
 * A piece of message content, such as text, an image, or a file.
 */
export const vUserMessageItemParamPropertiesContentOneof0Item = v.union([
  vInputTextContentParam,
  vInputImageContentParamAutoParam,
  vInputFileContentParam,
])

export const vUserMessageItemParam = v.object({
  id: v.nullish(v.string()),
  type: v.optional(v.picklist(['message']), 'message'),
  role: v.optional(v.picklist(['user']), 'user'),
  content: v.union([v.array(vUserMessageItemParamPropertiesContentOneof0Item), v.pipe(v.string(), v.maxLength(10485760))]),
  status: v.nullish(v.string()),
})

export const vSystemMessageItemParamPropertiesContentOneof0Item = vInputTextContentParam

export const vSystemMessageItemParam = v.object({
  id: v.nullish(v.string()),
  type: v.optional(v.picklist(['message']), 'message'),
  role: v.optional(v.picklist(['system']), 'system'),
  content: v.union([v.array(vSystemMessageItemParamPropertiesContentOneof0Item), v.pipe(v.string(), v.maxLength(10485760))]),
  status: v.nullish(v.string()),
})

export const vDeveloperMessageItemParamPropertiesContentOneof0Item = vInputTextContentParam

export const vDeveloperMessageItemParam = v.object({
  id: v.nullish(v.string()),
  type: v.optional(v.picklist(['message']), 'message'),
  role: v.optional(v.picklist(['developer']), 'developer'),
  content: v.union([v.array(vDeveloperMessageItemParamPropertiesContentOneof0Item), v.pipe(v.string(), v.maxLength(10485760))]),
  status: v.nullish(v.string()),
})

/**
 * A piece of assistant message content, such as text or a refusal.
 */
export const vAssistantMessageItemParamPropertiesContentOneof0Item = v.union([vOutputTextContentParam, vRefusalContentParam])

export const vAssistantMessageItemParam = v.object({
  id: v.nullish(v.string()),
  type: v.optional(v.picklist(['message']), 'message'),
  role: v.optional(v.picklist(['assistant']), 'assistant'),
  content: v.union([v.array(vAssistantMessageItemParamPropertiesContentOneof0Item), v.pipe(v.string(), v.maxLength(10485760))]),
  phase: v.optional(v.picklist(['commentary', 'final_answer'])),
  status: v.nullish(v.string()),
})

/**
 * A piece of message content, such as text, an image, or a file.
 */
export const vFunctionCallOutputItemParamPropertiesOutputOneof1Item = v.union([
  vInputTextContentParam,
  vInputImageContentParamAutoParam,
  vInputFileContentParam,
  vInputVideoContent,
])

/**
 * Function tool call output
 *
 * The output of a function tool call.
 */
export const vFunctionCallOutputItemParam = v.object({
  id: v.nullish(v.string()),
  call_id: v.pipe(v.string(), v.minLength(1), v.maxLength(64)),
  type: v.optional(v.picklist(['function_call_output']), 'function_call_output'),
  output: v.union([v.pipe(v.string(), v.maxLength(10485760)), v.array(vFunctionCallOutputItemParamPropertiesOutputOneof1Item)]),
  status: v.nullish(v.intersect([vFunctionCallStatus, v.unknown()])),
})

export const vItemParam = v.union([
  vItemReferenceParam,
  vReasoningItemParam,
  vCompactionSummaryItemParam,
  vUserMessageItemParam,
  vSystemMessageItemParam,
  vDeveloperMessageItemParam,
  vAssistantMessageItemParam,
  vFunctionCallItemParam,
  vFunctionCallOutputItemParam,
])

export const vCreateResponseBody = v.object({
  model: v.nullish(v.string()),
  input: v.nullish(v.union([v.pipe(v.string(), v.maxLength(10485760)), v.array(vItemParam)])),
  previous_response_id: v.nullish(v.string()),
  include: v.optional(v.array(vIncludeEnum)),
  tools: v.nullish(v.array(vResponsesToolParam)),
  tool_choice: v.nullish(v.intersect([vToolChoiceParam, v.unknown()])),
  metadata: v.nullish(v.intersect([vMetadataParam, v.unknown()])),
  text: v.nullish(v.intersect([vTextParam, v.unknown()])),
  temperature: v.nullish(v.number()),
  top_p: v.nullish(v.number()),
  presence_penalty: v.nullish(v.number()),
  frequency_penalty: v.nullish(v.number()),
  parallel_tool_calls: v.nullish(v.boolean()),
  stream: v.optional(v.boolean()),
  stream_options: v.nullish(v.intersect([vStreamOptionsParam, v.unknown()])),
  background: v.optional(v.boolean()),
  max_output_tokens: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(16))),
  max_tool_calls: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(1))),
  reasoning: v.nullish(v.intersect([vReasoningParam, v.unknown()])),
  safety_identifier: v.nullish(v.pipe(v.string(), v.maxLength(64))),
  prompt_cache_key: v.nullish(v.pipe(v.string(), v.maxLength(64))),
  truncation: v.optional(v.intersect([vTruncationEnum, v.unknown()])),
  instructions: v.nullish(v.string()),
  store: v.optional(v.boolean()),
  service_tier: v.optional(v.intersect([vServiceTierEnum, v.unknown()])),
  top_logprobs: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(20))),
})
