[build]
publish = "apps/moonshine-web/dist"
command = "pnpm run packages:stub && pnpm -F @proj-airi/moonshine-web run build"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
