export const animations = {
  agent007: new URL('./agent_007.vrma', import.meta.url).href,
  aiCatDance: new URL('./ai_cat_dance.vrma', import.meta.url).href,
  armsSwing: new URL('./arms_swing.vrma', import.meta.url).href,
  armsUpDownDance: new URL('./arms_up_down_dance.vrma', import.meta.url).href,
  blingBang: new URL('./bling_bang.vrma', import.meta.url).href,
  confidentPose: new URL('./confident_pose.vrma', import.meta.url).href,
  cool: new URL('./cool.vrma', import.meta.url).href,
  crabDance: new URL('./crab_dance.vrma', import.meta.url).href,
  energetic: new URL('./energetic.vrma', import.meta.url).href,
  flamboyant: new URL('./flamboyant.vrma', import.meta.url).href,
  grandstand: new URL('./grandstand.vrma', import.meta.url).href,
  hitoMania: new URL('./hito_mania.vrma', import.meta.url).href,
  humansAreJustCylinders: new URL('./humans_are_just_cylinders.vrma', import.meta.url).href,
  idleLoop: new URL('./idle_loop.vrma', import.meta.url).href,
  innocent: new URL('./innocent.vrma', import.meta.url).href,
  kawaiiKaiwai: new URL('./kawaii_kaiwai.vrma', import.meta.url).href,
  ladylake: new URL('./ladylake.vrma', import.meta.url).href,
  magicEyeWink: new URL('./magic_eye_wink.vrma', import.meta.url).href,
  peaceSign: new URL('./peace_sign.vrma', import.meta.url).href,
  powerful: new URL('./powerful.vrma', import.meta.url).href,
  showcase: new URL('./showcase.vrma', import.meta.url).href,
  shy: new URL('./shy.vrma', import.meta.url).href,
  sittingToWave: new URL('./sitting_to_wave.vrma', import.meta.url).href,
  tetris: new URL('./tetris.vrma', import.meta.url).href,
}
