[build]
base = "/"
command = "bun run --filter @proj-airi/ui-transitions build && bun run --filter @proj-airi/ui-transitions play:build"
publish = "/packages/ui-transitions/playground/dist"

[build.environment]
NODE_VERSION = "24"
NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
