[build]
base = "/"
command = "pnpm -F @proj-airi/ui-transitions run build && pnpm -F @proj-airi/ui-transitions run play:build"
publish = "/packages/ui-transitions/playground/dist"

[build.environment]
NODE_VERSION = "24.3.0"
NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
