name: teabag-attention
version: 1

trigger:
  modality: sighted
  kind: sneak_toggle
  where:
    entityType: player

accumulator:
  threshold: 5
  window: 2s
  mode: sliding

signal:
  type: entity_attention
  description: 'Player {{ displayName }} is teabagging (rapid sneaking)'
  confidence: 1.0
  metadata:
    action: teabag
    distance: '{{ distance }}'
    displayName: '{{ displayName }}'
