export type DoubaoVoiceCatalog = 'multilingual' | 'standard'

/** One official Doubao Speech 2.0 voice that supports bidirectional streaming. */
export interface DoubaoOfficialVoice {
  /** Official voice_type value sent as the StartSession speaker. */
  readonly id: string
  /** Official user-visible voice name. */
  readonly name: string
  /** Section of the official voice list that owns this voice. */
  readonly catalog: DoubaoVoiceCatalog
  /** Official usage scene text. */
  readonly scene: string
  /** Official language and dialect text. */
  readonly languages: string
}

type DoubaoOfficialVoiceRecord = readonly [
  catalog: DoubaoVoiceCatalog,
  name: string,
  id: string,
  scene: string,
  languages: string,
]

// Source: https://docs.volcengine.com/docs/6561/1257544?lang=zh
// Synchronized on 2026-08-27. Rows marked as unsupported by bidirectional
// streaming are not included.
const officialVoiceRecords = [
  ['standard', 'Vivi 2.0', 'zh_female_vv_uranus_bigtts', '通用场景', '语种：中文、日文、印尼、墨西哥西班牙语 方言：粤语、上海、河南、北京、天津、四川、陕西、东北'],
  ['standard', '小何 2.0', 'zh_female_xiaohe_uranus_bigtts', '通用场景', '语种：中文 方言：粤语、上海、河南、北京、天津、四川、陕西、东北'],
  ['standard', '云舟 2.0', 'zh_male_m191_uranus_bigtts', '通用场景', '语种：中文 方言：粤语、上海、河南、北京、天津、四川、陕西、东北'],
  ['standard', '小天 2.0', 'zh_male_taocheng_uranus_bigtts', '通用场景', '语种：中文 方言：粤语、上海、河南、北京、天津、四川、陕西、东北'],
  ['standard', '刘飞 2.0', 'zh_male_liufei_uranus_bigtts', '通用场景', '中文'],
  ['standard', '魅力苏菲 2.0', 'zh_female_sophie_uranus_bigtts', '通用场景', '中文'],
  ['standard', '清新女声 2.0', 'zh_female_qingxinnvsheng_uranus_bigtts', '通用场景', '中文'],
  ['standard', '知性灿灿 2.0', 'zh_female_cancan_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '撒娇学妹 2.0', 'zh_female_sajiaoxuemei_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '甜美小源 2.0', 'zh_female_tianmeixiaoyuan_uranus_bigtts', '通用场景', '中文'],
  ['standard', '甜美桃子 2.0', 'zh_female_tianmeitaozi_uranus_bigtts', '通用场景', '中文'],
  ['standard', '爽快思思 2.0', 'zh_female_shuangkuaisisi_uranus_bigtts', '通用场景', '中文'],
  ['standard', '佩奇猪 2.0', 'zh_female_peiqi_uranus_bigtts', '视频配音', '中文'],
  ['standard', '邻家女孩 2.0', 'zh_female_linjianvhai_uranus_bigtts', '通用场景', '中文'],
  ['standard', '少年梓辛 2.0', 'zh_male_shaonianzixin_uranus_bigtts', '通用场景', '中文'],
  ['standard', '猴哥 2.0', 'zh_male_sunwukong_uranus_bigtts', '视频配音', '中文'],
  ['standard', 'Tina老师 2.0', 'zh_female_yingyujiaoxue_uranus_bigtts', '教育场景', '中文、英式英语'],
  ['standard', '暖阳女声 2.0', 'zh_female_kefunvsheng_uranus_bigtts', '客服场景', '中文'],
  ['standard', '儿童绘本 2.0', 'zh_female_xiaoxue_uranus_bigtts', '有声阅读', '中文'],
  ['standard', '大壹 2.0', 'zh_male_dayi_uranus_bigtts', '视频配音', '中文'],
  ['standard', '黑猫侦探社咪仔 2.0', 'zh_female_mizai_uranus_bigtts', '视频配音', '中文'],
  ['standard', '鸡汤女 2.0', 'zh_female_jitangnv_uranus_bigtts', '视频配音', '中文'],
  ['standard', '魅力女友 2.0', 'zh_female_meilinvyou_uranus_bigtts', '通用场景', '中文'],
  ['standard', '流畅女声 2.0', 'zh_female_liuchangnv_uranus_bigtts', '视频配音', '中文'],
  ['standard', '儒雅逸辰 2.0', 'zh_male_ruyayichen_uranus_bigtts', '视频配音', '中文'],
  ['standard', 'Tim', 'en_male_tim_uranus_bigtts', '多语种', '美式英语'],
  ['standard', 'Dacey', 'en_female_dacey_uranus_bigtts', '多语种', '美式英语'],
  ['standard', 'Stokie', 'en_female_stokie_uranus_bigtts', '多语种', '美式英语'],
  ['standard', '温柔妈妈 2.0', 'zh_female_wenroumama_uranus_bigtts', '通用场景', '中文'],
  ['standard', '解说小明 2.0', 'zh_male_jieshuoxiaoming_uranus_bigtts', '通用场景', '中文'],
  ['standard', 'TVB女声 2.0', 'zh_female_tvbnv_uranus_bigtts', '通用场景', '中文'],
  ['standard', '译制片男 2.0', 'zh_male_yizhipiannan_uranus_bigtts', '通用场景', '中文'],
  ['standard', '俏皮女声 2.0', 'zh_female_qiaopinv_uranus_bigtts', '通用场景', '中文'],
  ['standard', '直率英子 2.0', 'zh_female_zhishuaiyingzi_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '邻家男孩 2.0', 'zh_male_linjiananhai_uranus_bigtts', '通用场景', '中文'],
  ['standard', '四郎 2.0', 'zh_male_silang_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '儒雅青年 2.0', 'zh_male_ruyaqingnian_uranus_bigtts', '通用场景', '中文'],
  ['standard', '擎苍 2.0', 'zh_male_qingcang_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '熊二 2.0', 'zh_male_xionger_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '樱桃丸子 2.0', 'zh_female_yingtaowanzi_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '温暖阿虎 2.0', 'zh_male_wennuanahu_uranus_bigtts', '通用场景', '中文'],
  ['standard', '奶气萌娃 2.0', 'zh_male_naiqimengwa_uranus_bigtts', '通用场景', '中文'],
  ['standard', '婆婆 2.0', 'zh_female_popo_uranus_bigtts', '通用场景', '中文'],
  ['standard', '高冷御姐 2.0', 'zh_female_gaolengyujie_uranus_bigtts', '通用场景', '中文'],
  ['standard', '傲娇霸总 2.0', 'zh_male_aojiaobazong_uranus_bigtts', '通用场景', '中文'],
  ['standard', '懒音绵宝 2.0', 'zh_male_lanyinmianbao_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '反卷青年 2.0', 'zh_male_fanjuanqingnian_uranus_bigtts', '通用场景', '中文'],
  ['standard', '温柔淑女 2.0', 'zh_female_wenroushunv_uranus_bigtts', '通用场景', '中文'],
  ['standard', '古风少御 2.0', 'zh_female_gufengshaoyu_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '活力小哥 2.0', 'zh_male_huolixiaoge_uranus_bigtts', '通用场景', '中文'],
  ['standard', '霸气青叔 2.0', 'zh_male_baqiqingshu_uranus_bigtts', '有声阅读', '中文'],
  ['standard', '悬疑解说 2.0', 'zh_male_xuanyijieshuo_uranus_bigtts', '有声阅读', '中文'],
  ['standard', '萌丫头 2.0', 'zh_female_mengyatou_uranus_bigtts', '通用场景', '中文'],
  ['standard', '贴心女声 2.0', 'zh_female_tiexinnvsheng_uranus_bigtts', '通用场景', '中文'],
  ['standard', '鸡汤妹妹 2.0', 'zh_female_jitangmei_uranus_bigtts', '通用场景', '中文'],
  ['standard', '磁性解说男声 2.0', 'zh_male_cixingjieshuonan_uranus_bigtts', '通用场景', '中文'],
  ['standard', '亮嗓萌仔 2.0', 'zh_male_liangsangmengzai_uranus_bigtts', '通用场景', '中文'],
  ['standard', '开朗姐姐 2.0', 'zh_female_kailangjiejie_uranus_bigtts', '通用场景', '中文'],
  ['standard', '高冷沉稳 2.0', 'zh_male_gaolengchenwen_uranus_bigtts', '通用场景', '中文'],
  ['standard', '深夜播客 2.0', 'zh_male_shenyeboke_uranus_bigtts', '通用场景', '中文'],
  ['standard', '鲁班七号 2.0', 'zh_male_lubanqihao_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '娇喘女声 2.0', 'zh_female_jiaochuannv_uranus_bigtts', '通用场景', '中文'],
  ['standard', '林潇 2.0', 'zh_female_linxiao_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '玲玲姐姐 2.0', 'zh_female_lingling_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '春日部姐姐 2.0', 'zh_female_chunribu_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '唐僧 2.0', 'zh_male_tangseng_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '庄周 2.0', 'zh_male_zhuangzhou_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '开朗弟弟 2.0', 'zh_male_kailangdidi_uranus_bigtts', '通用场景', '中文'],
  ['standard', '猪八戒 2.0', 'zh_male_zhubajie_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '感冒电音姐姐 2.0', 'zh_female_ganmaodianyin_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '谄媚女声 2.0', 'zh_female_chanmeinv_uranus_bigtts', '通用场景', '中文'],
  ['standard', '女雷神 2.0', 'zh_female_nvleishen_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '亲切女声 2.0', 'zh_female_qinqienv_uranus_bigtts', '通用场景', '中文'],
  ['standard', '快乐小东 2.0', 'zh_male_kuailexiaodong_uranus_bigtts', '通用场景', '中文'],
  ['standard', '开朗学长 2.0', 'zh_male_kailangxuezhang_uranus_bigtts', '通用场景', '中文'],
  ['standard', '悠悠君子 2.0', 'zh_male_youyoujunzi_uranus_bigtts', '通用场景', '中文'],
  ['standard', '文静毛毛 2.0', 'zh_female_wenjingmaomao_uranus_bigtts', '通用场景', '中文'],
  ['standard', '知性女声 2.0', 'zh_female_zhixingnv_uranus_bigtts', '通用场景', '中文'],
  ['standard', '清爽男大 2.0', 'zh_male_qingshuangnanda_uranus_bigtts', '通用场景', '中文'],
  ['standard', '渊博小叔 2.0', 'zh_male_yuanboxiaoshu_uranus_bigtts', '通用场景', '中文'],
  ['standard', '阳光青年 2.0', 'zh_male_yangguangqingnian_uranus_bigtts', '通用场景', '中文'],
  ['standard', '清澈梓梓 2.0', 'zh_female_qingchezizi_uranus_bigtts', '通用场景', '中文'],
  ['standard', '甜美悦悦 2.0', 'zh_female_tianmeiyueyue_uranus_bigtts', '通用场景', '中文'],
  ['standard', '心灵鸡汤 2.0', 'zh_female_xinlingjitang_uranus_bigtts', '通用场景', '中文'],
  ['standard', '温柔小哥 2.0', 'zh_male_wenrouxiaoge_uranus_bigtts', '通用场景', '中文'],
  ['standard', '柔美女友 2.0', 'zh_female_roumeinvyou_uranus_bigtts', '通用场景', '中文'],
  ['standard', '东方浩然 2.0', 'zh_male_dongfanghaoran_uranus_bigtts', '通用场景', '中文'],
  ['standard', '温柔小雅 2.0', 'zh_female_wenrouxiaoya_uranus_bigtts', '通用场景', '中文'],
  ['standard', '天才童声 2.0', 'zh_male_tiancaitongsheng_uranus_bigtts', '通用场景', '中文'],
  ['standard', '武则天 2.0', 'zh_female_wuzetian_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '顾姐 2.0', 'zh_female_gujie_uranus_bigtts', '角色扮演', '中文'],
  ['standard', '广告解说 2.0', 'zh_male_guanggaojieshuo_uranus_bigtts', '通用场景', '中文'],
  ['standard', '少儿故事 2.0', 'zh_female_shaoergushi_uranus_bigtts', '有声阅读', '中文'],
  ['standard', 'Charlie 2.0', 'ICL_uranus_en_female_charlie_tob', '多语种', '美式英语'],
  ['standard', 'Ethan 2.0', 'ICL_uranus_en_male_ethan_tob', '多语种', '澳洲英语'],
  ['standard', 'Alastor 2.0', 'ICL_uranus_en_male_alastor_tob', '多语种', '英式英语'],
  ['standard', 'Chucky 2.0', 'ICL_uranus_en_male_chucky_tob', '多语种', '美式英语'],
  ['standard', 'Noah 2.0', 'ICL_uranus_en_male_noah_tob', '多语种', '美式英语'],
  ['standard', 'Jigsaw 2.0', 'ICL_uranus_en_male_jigsaw_tob', '多语种', '美式英语'],
  ['standard', 'Clown Man 2.0', 'ICL_uranus_en_male_clown_man_tob', '多语种', '美式英语'],
  ['standard', 'Cartoon Chef 2.0', 'ICL_uranus_en_male_cartoon_chef_tob', '多语种', '美式英语'],
  ['standard', 'Frosty Man 2.0', 'ICL_uranus_en_male_frosty_man_tob', '多语种', '美式英语'],
  ['standard', 'The Grinch 2.0', 'ICL_uranus_en_male_the_grinch_tob', '多语种', '美式英语'],
  ['standard', 'Kevin McCallister 2.0', 'ICL_uranus_en_male_kevin_mccallister_tob', '多语种', '美式英语'],
  ['standard', 'Michael 2.0', 'ICL_uranus_en_male_michael_tob', '多语种', '美式英语'],
  ['standard', 'Big Boogie 2.0', 'ICL_uranus_en_male_big_boogie_tob', '多语种', '美式英语'],
  ['standard', 'Xavier 2.0', 'ICL_uranus_en_male_xavier_tob', '多语种', '美式英语'],
  ['standard', 'Zayne 2.0', 'ICL_uranus_en_male_zayne_tob', '多语种', '美式英语'],
  ['standard', '客服婉君 2.0', 'ICL_uranus_zh_female_kefuwanjun_tob', '客服场景', '中文'],
  ['standard', '营销小楠 2.0', 'ICL_uranus_zh_female_yingxiaokefu_v2_tob', '客服场景', '中文'],
  ['standard', '傲娇女友 2.0', 'ICL_uranus_zh_female_aojiaonvyou_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '傲慢娇声 2.0', 'ICL_uranus_zh_female_aomanjiaosheng_tob', '角色扮演', '中文'],
  ['standard', '邪魅女王 2.0', 'ICL_uranus_zh_female_xiemeinvwang_tob', '角色扮演', '中文'],
  ['standard', '病娇姐姐 2.0', 'ICL_uranus_zh_female_bingjiaojiejie_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '病娇萌妹 2.0', 'ICL_uranus_zh_female_bingjiaomengmei_tob', '角色扮演', '中文'],
  ['standard', '病弱少女 2.0', 'ICL_uranus_zh_female_bingruoshaonv_tob', '角色扮演', '中文'],
  ['standard', '成熟温柔 2.0', 'ICL_uranus_zh_female_chengshuwenrou_tob', '角色扮演', '中文'],
  ['standard', '成熟姐姐 2.0', 'ICL_uranus_zh_female_chengshujiejie_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '纯真少女 2.0', 'ICL_uranus_zh_female_chunzhenshaonv_tob', '角色扮演', '中文'],
  ['standard', '纯澈女生 2.0', 'ICL_uranus_zh_female_chunchenvsheng_tob', '通用场景', '中文'],
  ['standard', '妩媚可人 2.0', 'ICL_uranus_zh_female_wumeikeren_tob', '角色扮演', '中文'],
  ['standard', '乖巧可儿 2.0', 'ICL_uranus_zh_female_guaiqiaokeer_tob', '客服场景', '中文'],
  ['standard', '和蔼奶奶 2.0', 'ICL_uranus_zh_female_heainainai_tob', '视频配音', '中文'],
  ['standard', '活泼刁蛮 2.0', 'ICL_uranus_zh_female_huopodiaoman_tob', '角色扮演', '中文'],
  ['standard', '活泼女孩 2.0', 'ICL_uranus_zh_female_huoponvhai_tob', '角色扮演', '中文'],
  ['standard', '娇憨女王 2.0', 'ICL_uranus_zh_female_jiaohannvwang_tob', '角色扮演', '中文'],
  ['standard', '娇弱萝莉 2.0', 'ICL_uranus_zh_female_jiaoruoluoli_tob', '角色扮演', '中文'],
  ['standard', '假小子 2.0', 'ICL_uranus_zh_female_jiaxiaozi_tob', '角色扮演', '中文'],
  ['standard', '精灵向导 2.0', 'ICL_uranus_zh_female_jinglingxiangdao_tob', '角色扮演', '中文'],
  ['standard', '开朗婷婷 2.0', 'ICL_uranus_zh_female_kailangtingting_tob', '客服场景', '中文'],
  ['standard', '开心小鸿 2.0', 'ICL_uranus_zh_female_kaixinxiaohong_tob', '客服场景', '中文'],
  ['standard', '可爱女生 2.0', 'ICL_uranus_zh_female_keainvsheng_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '灵动欣欣 2.0', 'ICL_uranus_zh_female_lingdongxinxin_tob', '客服场景', '中文'],
  ['standard', '邻居阿姨 2.0', 'ICL_uranus_zh_female_linjuayi_tob', '视频配音', '中文'],
  ['standard', '甜美娇俏 2.0', 'ICL_uranus_zh_female_tianmeijiaoqiao_tob', '角色扮演', '中文'],
  ['standard', '清冷高雅 2.0', 'ICL_uranus_zh_female_qinglenggaoya_tob', '角色扮演', '中文'],
  ['standard', '理性圆子 2.0', 'ICL_uranus_zh_female_lixingyuanzi_tob', '客服场景', '中文'],
  ['standard', '性感魅惑 2.0', 'ICL_uranus_zh_female_xingganmeihuo_tob', '角色扮演', '中文'],
  ['standard', '暖心茜茜 2.0', 'ICL_uranus_zh_female_nuanxinqianqian_tob', '客服场景', '中文'],
  ['standard', '暖心学姐 2.0', 'ICL_uranus_zh_female_nuanxinxuejie_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '清甜莓莓 2.0', 'ICL_uranus_zh_female_qingtianmeimei_tob', '客服场景', '中文'],
  ['standard', '清甜桃桃 2.0', 'ICL_uranus_zh_female_qingtiantaotao_tob', '客服场景', '中文'],
  ['standard', '清晰小雪 2.0', 'ICL_uranus_zh_female_qingxixiaoxue_tob', '客服场景', '中文'],
  ['standard', '倾心少女 2.0', 'ICL_uranus_zh_female_qingxinshaonv_tob', '视频配音', '中文'],
  ['standard', '柔骨魂师 2.0', 'ICL_uranus_zh_female_rouguhunshi_tob', '角色扮演', '中文'],
  ['standard', '软萌糖糖 2.0', 'ICL_uranus_zh_female_ruanmengtangtang_tob', '客服场景', '中文'],
  ['standard', '软萌团子 2.0', 'ICL_uranus_zh_female_ruanmengtuanzi_tob', '客服场景', '中文'],
  ['standard', '甜美活泼 2.0', 'ICL_uranus_zh_female_tianmeihuopo_tob', '角色扮演', '中文'],
  ['standard', '甜美小橘 2.0', 'ICL_uranus_zh_female_tianmeixiaoju_tob', '客服场景', '中文'],
  ['standard', '甜美小雨 2.0', 'ICL_uranus_zh_female_tianmeixiaoyu_tob', '客服场景', '中文'],
  ['standard', '调皮公主 2.0', 'ICL_uranus_zh_female_tiaopigongzhu_tob', '角色扮演', '中文'],
  ['standard', '贴心女友 2.0', 'ICL_uranus_zh_female_tiexinnvyou_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '温柔女神 2.0', 'ICL_uranus_zh_female_wenrounvshen_tob', '通用场景', '中文'],
  ['standard', '温柔文雅 2.0', 'ICL_uranus_zh_female_wenrouwenya_tob', '通用场景,S2S-SC', '中文'],
  ['standard', '知心姐姐 2.0', 'ICL_uranus_zh_female_zhixinjiejie_tob', '通用场景', '中文'],
  ['standard', '妩媚御姐 2.0', 'ICL_uranus_zh_female_wumeiyujie_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '元气甜妹 2.0', 'ICL_uranus_zh_female_yuanqitianmei_tob', '通用场景', '中文'],
  ['standard', '邪魅御姐 2.0', 'ICL_uranus_zh_female_xiemeiyujie_tob', '角色扮演', '中文'],
  ['standard', '性感御姐 2.0', 'ICL_uranus_zh_female_xingganyujie_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '秀丽倩倩 2.0', 'ICL_uranus_zh_female_xiuliqianqian_tob', '客服场景', '中文'],
  ['standard', '贴心闺蜜 2.0', 'ICL_uranus_zh_female_tiexinguimi_tob', '通用场景', '中文'],
  ['standard', '贴心妹妹 2.0', 'ICL_uranus_zh_female_tiexinmeimei_tob', '通用场景', '中文'],
  ['standard', '温柔白月光 2.0', 'ICL_uranus_zh_female_wenroubaiyueguang_tob', '通用场景', '中文'],
  ['standard', '初恋女友 2.0', 'ICL_uranus_zh_female_chuliannvyou_tob', '通用场景', '中文'],
  ['standard', '知性温婉 2.0', 'ICL_uranus_zh_female_zhixingwenwan_tob', '通用场景', '中文'],
  ['standard', '傲气凌人 2.0', 'ICL_uranus_zh_male_aoqilingren_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '黯刃秦主 2.0', 'ICL_uranus_zh_male_anrenqinzhu_tob', '角色扮演', '中文'],
  ['standard', '傲娇公子 2.0', 'ICL_uranus_zh_male_aojiaogongzi_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '傲娇精英 2.0', 'ICL_uranus_zh_male_aojiaojingying_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '傲慢青年 2.0', 'ICL_uranus_zh_male_aomanqingnian_tob', '角色扮演', '中文'],
  ['standard', '傲慢少爷 2.0', 'ICL_uranus_zh_male_aomanshaoye_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '枕边低语 2.0', 'ICL_uranus_zh_male_zhenbiandiyu_tob', '角色扮演', '中文'],
  ['standard', '霸道少爷 2.0', 'ICL_uranus_zh_male_badaoshaoye_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '霸道总裁 2.0', 'ICL_uranus_zh_male_badaozongcai_tob', '角色扮演', '中文'],
  ['standard', '病娇白莲 2.0', 'ICL_uranus_zh_male_bingjiaobailian_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '病娇弟弟 2.0', 'ICL_uranus_zh_male_bingjiaodidi_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '病娇哥哥 2.0', 'ICL_uranus_zh_male_bingjiaogege_tob', '角色扮演', '中文'],
  ['standard', '病娇男友 2.0', 'ICL_uranus_zh_male_bingjiaonanyou_tob', '角色扮演', '中文'],
  ['standard', '病娇少年 2.0', 'ICL_uranus_zh_male_bingjiaoshaonian_tob', '角色扮演', '中文'],
  ['standard', '病弱公子 2.0', 'ICL_uranus_zh_male_bingruogongzi_tob', '角色扮演', '中文'],
  ['standard', '病弱少年 2.0', 'ICL_uranus_zh_male_bingruoshaonian_tob', '角色扮演', '中文'],
  ['standard', '不羁青年 2.0', 'ICL_uranus_zh_male_bujiqingnian_tob', '角色扮演', '中文'],
  ['standard', '醇厚低音 2.0', 'ICL_uranus_zh_male_chunhoudiyin_tob', '视频配音', '中文'],
  ['standard', '咆哮小哥 2.0', 'ICL_uranus_zh_male_paoxiaoxiaoge_tob', '视频配音', '中文'],
  ['standard', '炀炀 2.0', 'ICL_uranus_zh_male_yangyang_tob', '通用场景', '中文'],
  ['standard', '孱弱少爷 2.0', 'ICL_uranus_zh_male_chanruoshaoye_tob', '角色扮演', '中文'],
  ['standard', '成熟总裁 2.0', 'ICL_uranus_zh_male_chengshuzongcai_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '沉稳明仔 2.0', 'ICL_uranus_zh_male_chenwenmingzai_tob', '客服场景', '中文'],
  ['standard', '清逸苏感 2.0', 'ICL_uranus_zh_male_qingyisugan_tob', '角色扮演', '中文'],
  ['standard', '纯真学弟 2.0', 'ICL_uranus_zh_male_chunzhenxuedi_tob', '角色扮演', '中文'],
  ['standard', '磁性男嗓 2.0', 'ICL_uranus_zh_male_cixingnansang_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '醋精男生 2.0', 'ICL_uranus_zh_male_cujingnansheng_tob', '角色扮演', '中文'],
  ['standard', '醋精男友 2.0', 'ICL_uranus_zh_male_cujingnanyou_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '低音沉郁 2.0', 'ICL_uranus_zh_male_diyinchenyu_tob', '角色扮演', '中文'],
  ['standard', '风发少年 2.0', 'ICL_uranus_zh_male_fengfashaonian_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '儒雅公子 2.0', 'ICL_uranus_zh_male_ruyagongzi_tob', '有声阅读', '中文'],
  ['standard', '腹黑公子 2.0', 'ICL_uranus_zh_male_fuheigongzi_tob', '角色扮演,S2S-SC', '中文'],
  ['standard', '干净少年 2.0', 'ICL_uranus_zh_male_ganjingshaonian_tob', '角色扮演', '中文'],
  ['standard', '高冷总裁 2.0', 'ICL_uranus_zh_male_gaolengzongcai_tob', '角色扮演', '中文'],
  ['standard', '孤傲公子 2.0', 'ICL_uranus_zh_male_guaogongzi_tob', '角色扮演', '中文'],
  ['standard', '孤高公子 2.0', 'ICL_uranus_zh_male_gugaogongzi_tob', '角色扮演', '中文'],
  ['standard', '诡异神秘 2.0', 'ICL_uranus_zh_male_guiyishenmi_tob', '角色扮演', '中文'],
  ['standard', '固执病娇 2.0', 'ICL_uranus_zh_male_guzhibingjiao_tob', '角色扮演', '中文'],
  ['standard', '憨厚敦实 2.0', 'ICL_uranus_zh_male_hanhoudunshi_tob', '角色扮演', '中文'],
  ['standard', '活力青年 2.0', 'ICL_uranus_zh_male_huoliqingnian_tob', '角色扮演', '中文'],
  ['standard', '活泼男友 2.0', 'ICL_uranus_zh_male_huoponanyou_tob', '角色扮演', '中文'],
  ['standard', '活泼爽朗 2.0', 'ICL_uranus_zh_male_huoposhuanglang_tob', '通用场景', '中文'],
  ['standard', '胡子叔叔 2.0', 'ICL_uranus_zh_male_huzishushu_tob', '角色扮演', '中文'],
  ['standard', '机甲智能 2.0', 'ICL_uranus_zh_male_jijiazhineng_tob', '角色扮演', '中文'],
  ['standard', '精英青年 2.0', 'ICL_uranus_zh_male_jingyingqingnian_tob', '角色扮演', '中文'],
  ['standard', '俊逸公子 2.0', 'ICL_uranus_zh_male_junyigongzi_tob', '角色扮演', '中文'],
  ['standard', '开朗轻快 2.0', 'ICL_uranus_zh_male_kailangqingkuai_tob', '通用场景', '中文'],
  ['standard', '开朗青年 2.0', 'ICL_uranus_zh_male_kailangqingnian_tob', '角色扮演', '中文'],
  ['standard', '蓝银草魂师 2.0', 'ICL_uranus_zh_male_lanyincaohunshi_tob', '角色扮演', '中文'],
  ['standard', '冷傲总裁 2.0', 'ICL_uranus_zh_male_lengaozongcai_tob', '角色扮演', '中文'],
  ['standard', '冷淡疏离 2.0', 'ICL_uranus_zh_male_lengdanshuli_tob', '角色扮演', '中文'],
  ['standard', '冷峻高智 2.0', 'ICL_uranus_zh_male_lengjungaozhi_tob', '角色扮演', '中文'],
  ['standard', '冷峻上司 2.0', 'ICL_uranus_zh_male_lengjunshangsi_tob', '角色扮演', '中文'],
  ['standard', '冷酷哥哥 2.0', 'ICL_uranus_zh_male_lengkugege_tob', '通用场景', '中文'],
  ['standard', '冷脸兄长 2.0', 'ICL_uranus_zh_male_lenglianxiongzhang_tob', '角色扮演', '中文'],
  ['standard', '冷脸学霸 2.0', 'ICL_uranus_zh_male_lenglianxueba_tob', '角色扮演', '中文'],
  ['standard', '冷漠男友 2.0', 'ICL_uranus_zh_male_lengmonanyou_tob', '角色扮演', '中文'],
  ['standard', '冷漠兄长 2.0', 'ICL_uranus_zh_male_lengmoxiongzhang_tob', '角色扮演', '中文'],
  ['standard', '凌云青年 2.0', 'ICL_uranus_zh_male_lingyunqingnian_tob', '角色扮演', '中文'],
  ['standard', '清冷矜贵 2.0', 'ICL_uranus_zh_male_qinglengjingui_tob', '角色扮演', '中文'],
  ['standard', '绿茶小哥 2.0', 'ICL_uranus_zh_male_lvchaxiaoge_tob', '角色扮演', '中文'],
  ['standard', '懵懂青年 2.0', 'ICL_uranus_zh_male_mengdongqingnian_tob', '角色扮演', '中文'],
  ['standard', '闷油瓶小哥 2.0', 'ICL_uranus_zh_male_menyoupingxiaoge_tob', '角色扮演', '中文'],
  ['standard', '嚣张小哥 2.0', 'ICL_uranus_zh_male_xiaozhangxiaoge_tob', '角色扮演', '中文'],
  ['standard', '粘人男友 2.0', 'ICL_uranus_zh_male_nianrennanyou_tob', '角色扮演', '中文'],
  ['standard', '内敛才俊 2.0', 'ICL_uranus_zh_male_neiliancaijun_tob', '有声阅读', '中文'],
  ['standard', '暖心体贴 2.0', 'ICL_uranus_zh_male_nuanxintitie_tob', '通用场景', '中文'],
  ['standard', '翩翩公子 2.0', 'ICL_uranus_zh_male_pianpiangongzi_tob', '角色扮演', '中文'],
  ['standard', '沉稳优雅 2.0', 'ICL_uranus_zh_male_chenwenyouya_tob', '角色扮演', '中文'],
  ['standard', '青涩小生 2.0', 'ICL_uranus_zh_male_qingsexiaosheng_tob', '角色扮演', '中文'],
  ['standard', '青涩青年 2.0', 'ICL_uranus_zh_male_qingseqingnian_tob', '角色扮演', '中文'],
  ['standard', '清爽少年 2.0', 'ICL_uranus_zh_male_qingshuangshaonian_tob', '角色扮演', '中文'],
  ['standard', '清新波波 2.0', 'ICL_uranus_zh_male_qingxinbobo_tob', '客服场景', '中文'],
  ['standard', '亲切青年 2.0', 'ICL_uranus_zh_male_qinqieqingnian_tob', '角色扮演', '中文'],
  ['standard', '亲切小卓 2.0', 'ICL_uranus_zh_male_qinqiexiaozhuo_tob', '客服场景', '中文'],
  ['standard', '清朗温润 2.0', 'ICL_uranus_zh_male_qinglangwenrun_tob', '角色扮演', '中文'],
  ['standard', '热血少年 2.0', 'ICL_uranus_zh_male_rexueshaonian_tob', '角色扮演', '中文'],
  ['standard', '儒雅才俊 2.0', 'ICL_uranus_zh_male_ruyacaijun_tob', '角色扮演', '中文'],
  ['standard', '儒雅君子 2.0', 'ICL_uranus_zh_male_ruyajunzi_tob', '角色扮演', '中文'],
  ['standard', '儒雅总裁 2.0', 'ICL_uranus_zh_male_ruyazongcai_tob', '角色扮演', '中文'],
  ['standard', '撒娇男生 2.0', 'ICL_uranus_zh_male_sajiaonansheng_tob', '角色扮演', '中文'],
  ['standard', '撒娇男友 2.0', 'ICL_uranus_zh_male_sajiaonanyou_tob', '角色扮演', '中文'],
  ['standard', '撒娇粘人 2.0', 'ICL_uranus_zh_male_sajiaonianren_tob', '角色扮演', '中文'],
  ['standard', '洒脱青年 2.0', 'ICL_uranus_zh_male_satuoqingnian_tob', '角色扮演', '中文'],
  ['standard', '少年将军 2.0', 'ICL_uranus_zh_male_shaonianjiangjun_tob', '角色扮演', '中文'],
  ['standard', '深沉总裁 2.0', 'ICL_uranus_zh_male_shenchenzongcai_tob', '角色扮演', '中文'],
  ['standard', '机灵小伙 2.0', 'ICL_uranus_zh_male_jilingxiaohuo_tob', '通用场景', '中文'],
  ['standard', '神秘法师 2.0', 'ICL_uranus_zh_male_shenmifashi_tob', '角色扮演', '中文'],
  ['standard', '率真小伙 2.0', 'ICL_uranus_zh_male_shuaizhenxiaohuo_tob', '通用场景', '中文'],
  ['standard', '爽朗小阳 2.0', 'ICL_uranus_zh_male_shuanglangxiaoyang_tob', '客服场景', '中文'],
  ['standard', '低沉缱绻 2.0', 'ICL_uranus_zh_male_dichenqianquan_tob', '角色扮演', '中文'],
  ['standard', '斯文青年 2.0', 'ICL_uranus_zh_male_siwenqingnian_tob', '角色扮演', '中文'],
  ['standard', '甜系男友 2.0', 'ICL_uranus_zh_male_tianxinanyou_tob', '角色扮演', '中文'],
  ['standard', '贴心男友 2.0', 'ICL_uranus_zh_male_tiexinnanyou_tob', '角色扮演', '中文'],
  ['standard', '温柔男同桌 2.0', 'ICL_uranus_zh_male_wenrounantongzhuo_tob', '角色扮演', '中文'],
  ['standard', '温柔男友 2.0', 'ICL_uranus_zh_male_wenrounanyou_tob', '角色扮演', '中文'],
  ['standard', '温柔学长 2.0', 'ICL_uranus_zh_male_wenrouxuezhang_tob', '角色扮演', '中文'],
  ['standard', '温润学者 2.0', 'ICL_uranus_zh_male_wenrunxuezhe_tob', '角色扮演', '中文'],
  ['standard', '温顺少年 2.0', 'ICL_uranus_zh_male_wenshunshaonian_tob', '角色扮演', '中文'],
  ['standard', '寡言小哥 2.0', 'ICL_uranus_zh_male_guayanxiaoge_tob', '角色扮演', '中文'],
  ['standard', '小侯爷 2.0', 'ICL_uranus_zh_male_xiaohouye_tob', '角色扮演', '中文'],
  ['standard', '奶气小生 2.0', 'ICL_uranus_zh_male_naiqixiaosheng_tob', '角色扮演', '中文'],
  ['standard', '潇洒随性 2.0', 'ICL_uranus_zh_male_xiaosasuixing_tob', '角色扮演', '中文'],
  ['standard', '温柔内敛 2.0', 'ICL_uranus_zh_male_wenrouneilian_tob', '角色扮演', '中文'],
  ['standard', '学霸男同桌 2.0', 'ICL_uranus_zh_male_xuebanantongzhuo_tob', '角色扮演', '中文'],
  ['standard', '学霸同桌 2.0', 'ICL_uranus_zh_male_xuebatongzhuo_tob', '角色扮演', '中文'],
  ['standard', '阳光洋洋 2.0', 'ICL_uranus_zh_male_yangguangyangyang_tob', '客服场景', '中文'],
  ['standard', '温暖少年 2.0', 'ICL_uranus_zh_male_wennuanshaonian_tob', '有声阅读', '中文'],
  ['standard', '意气少年 2.0', 'ICL_uranus_zh_male_yiqishaonian_tob', '角色扮演', '中文'],
  ['standard', '油腻大叔 2.0', 'ICL_uranus_zh_male_younidashu_tob', '角色扮演', '中文'],
  ['standard', '幽默大爷 2.0', 'ICL_uranus_zh_male_youmodaye_tob', '角色扮演', '中文'],
  ['standard', '幽默叔叔 2.0', 'ICL_uranus_zh_male_youmoshushu_tob', '角色扮演', '中文'],
  ['standard', '优柔帮主 2.0', 'ICL_uranus_zh_male_youroubangzhu_tob', '角色扮演', '中文'],
  ['standard', '优柔公子 2.0', 'ICL_uranus_zh_male_yourougongzi_tob', '角色扮演', '中文'],
  ['standard', '元气少年 2.0', 'ICL_uranus_zh_male_yuanqishaonian_tob', '角色扮演', '中文'],
  ['standard', '仗剑君子 2.0', 'ICL_uranus_zh_male_zhangjianjunzi_tob', '角色扮演', '中文'],
  ['standard', '仗剑侠客 2.0', 'ICL_uranus_zh_male_zhangjianxiake_tob', '角色扮演', '中文'],
  ['standard', '正直青年 2.0', 'ICL_uranus_zh_male_zhengzhiqingnian_tob', '角色扮演', '中文'],
  ['standard', '直率青年 2.0', 'ICL_uranus_zh_male_zhishuaiqingnian_tob', '角色扮演', '中文'],
  ['standard', '中二青年 2.0', 'ICL_uranus_zh_male_zhongerqingnian_tob', '角色扮演', '中文'],
  ['standard', '自负青年 2.0', 'ICL_uranus_zh_male_zifuqingnian_tob', '角色扮演', '中文'],
  ['standard', '自信青年 2.0', 'ICL_uranus_zh_male_zixinqingnian_tob', '角色扮演', '中文'],
  ['standard', '天才同桌 2.0', 'ICL_uranus_zh_male_tiancaitongzhuo_tob', '角色扮演', '中文'],
  ['standard', '清新沐沐 2.0', 'ICL_uranus_zh_male_qingxinmumu_tob', '客服场景', '中文'],
  ['standard', '温婉珊珊 2.0', 'ICL_uranus_zh_female_wenwanshanshan_tob', '客服场景', '中文'],
  ['standard', '热情艾娜 2.0', 'ICL_uranus_zh_female_reqingaina_tob', '客服场景', '中文'],
  ['standard', '爽朗少年 2.0', 'ICL_uranus_zh_male_shuanglangshaonian_tob', '角色扮演', '中文'],
  ['standard', '轻盈朵朵 2.0', 'ICL_uranus_zh_female_qingyingduoduo_tob', '客服场景', '中文'],
  ['multilingual', 'Dina', 'ar_female_dina_uranus_bigtts', '通用场景, 视频配音,多语种,阿拉伯语', '阿拉伯语'],
  ['multilingual', 'Fatma', 'ar_female_fatma_uranus_bigtts', '趣味口音,多语种,阿拉伯语', '阿拉伯语'],
  ['multilingual', 'Youssef', 'ar_male_youssef_uranus_bigtts', '通用场景,有声阅读,多语种,阿拉伯语', '阿拉伯语'],
  ['multilingual', 'Stella', 'de_female_bv081_uranus_bigtts', '教学场景, 客服场景,多语种,德语', '德语'],
  ['multilingual', 'Rowan', 'en_male_adam-imitation_uranus_bigtts', '通用场景,有声阅读,美式英语,多语种', '美式英语'],
  ['multilingual', 'Alberto', 'en_male_alberto_uranus_bigtts', '通用场景, 教学场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'Alex', 'en_male_alex_uranus_bigtts', '通用场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Allison', 'en_female_allison_uranus_bigtts', '视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Charlotte', 'en_female_authoritative-british_uranus_bigtts', '教学场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Margaret', 'en_female_authoritative-informative_uranus_bigtts', '通用场景,有声阅读,美式英语,多语种', '美式英语'],
  ['multilingual', 'Jones', 'en_male_bill-jones_uranus_bigtts', '趣味口音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Brad_Pitt', 'en_male_brad_pitt_p1_uranus_bigtts', '通用场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Brittney', 'en_female_brittney_uranus_bigtts', '通用场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Adrian', 'en_male_bruce_uranus_bigtts', '通用场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Leo', 'en_male_chandler_p1_uranus_bigtts', '趣味口音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Bob', 'en_male_cowboy-bob_uranus_bigtts', '通用场景, 教学场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'David', 'en_male_david_uranus_bigtts', '通用场景,有声阅读,美式英语,多语种', '美式英语'],
  ['multilingual', 'Orion', 'en_male_deep-voice_uranus_bigtts', '趣味口音, 角色扮演,美式英语,多语种', '美式英语'],
  ['multilingual', 'Julian', 'en_male_diyuwenrounan_uranus_bigtts', '有声阅读,美式英语,多语种', '美式英语'],
  ['multilingual', 'Harrison', 'en_male_evil-guy-oxley_uranus_bigtts', '视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Jasper', 'en_male_excited-male-voice_uranus_bigtts', '趣味口音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Alfred', 'en_male_father-christmas_uranus_bigtts', '通用场景,有声阅读, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Holly', 'en_female_female_tutor_ms-jenny_uranus_bigtts', '教学场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Felix', 'en_male_fernando-martinez_uranus_bigtts', '通用场景, 教学场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'Godfather', 'en_male_godfather_uranus_bigtts', '有声阅读, 角色扮演,美式英语,多语种', '美式英语'],
  ['multilingual', 'Gollum', 'en_male_gollum_uranus_bigtts', '角色扮演,美式英语,多语种', '美式英语'],
  ['multilingual', 'Beau', 'en_male_hades_uranus_bigtts', '通用场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Hayley', 'en_female_hayley_uranus_bigtts', '教学场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Jamie', 'en_male_jamie_uranus_bigtts', '通用场景, 教学场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Jane', 'en_female_jane_uranus_bigtts', '视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Jenny', 'en_female_jenny_uranus_bigtts', '通用场景, 客服场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'Blaze', 'en_male_jidongchuanjiaoshi_uranus_bigtts', '趣味口音, 角色扮演,美式英语,多语种', '美式英语'],
  ['multilingual', 'Jimmy', 'en_male_jimmy_uranus_bigtts', '通用场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Joanne', 'en_female_joanne_uranus_bigtts', '通用场景,有声阅读, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Joker', 'en_male_joker_uranus_bigtts', '趣味口音, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Josh', 'en_male_josh_uranus_bigtts', '视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Kevin', 'en_male_kevin_uranus_bigtts', '教学场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Knightley', 'en_male_knightley_uranus_bigtts', '有声阅读,美式英语,多语种', '美式英语'],
  ['multilingual', 'Lynn', 'en_female_lana_del_rey_kelley_d_p1_uranus_bigtts', '角色扮演,美式英语,多语种', '美式英语'],
  ['multilingual', 'Ivy', 'en_female_lana_del_rey_parky_s_p1_uranus_bigtts', '客服场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'Marcus', 'en_male_marcus_uranus_bigtts', '通用场景,有声阅读,美式英语,多语种', '美式英语'],
  ['multilingual', 'Mel', 'en_female_mel_uranus_bigtts', '教学场景, 客服场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'Hank', 'en_male_michael_uranus_bigtts', '通用场景, 教学场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'Chip', 'en_male_michael-mouse_uranus_bigtts', '趣味口音, 角色扮演,美式英语,多语种', '美式英语'],
  ['multilingual', 'Rory', 'en_male_motivational-coach_uranus_bigtts', '趣味口音, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Myra', 'en_female_myra_uranus_bigtts', '教学场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'Blair', 'en_female_nadia_uranus_bigtts', '通用场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Elaine', 'en_female_pleasant-female_uranus_bigtts', '有声阅读,视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Rachel', 'en_female_rachel_p1_uranus_bigtts', '趣味口音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Ronald', 'en_male_ronald_uranus_bigtts', '有声阅读,美式英语,多语种', '美式英语'],
  ['multilingual', 'Russell', 'en_male_russell_uranus_bigtts', '通用场景, 教学场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'Scarlet', 'en_female_scarlet_p1_uranus_bigtts', '客服场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'Sharron', 'en_female_sharron_uranus_bigtts', '趣味口音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Simba', 'en_male_simba_p1_uranus_bigtts', '通用场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Skye', 'en_female_skye_uranus_bigtts', '通用场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'Tom', 'en_male_tom_hiddleston_p1_uranus_bigtts', '通用场景,有声阅读,美式英语,多语种', '美式英语'],
  ['multilingual', 'Valentino', 'en_male_valentino_uranus_bigtts', '通用场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Megan', 'en_female_wenrouzhishijieshuonv_uranus_bigtts', '客服场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'Kayla', 'en_female_xinwenjieshuonv_uranus_bigtts', '角色扮演,美式英语,多语种', '美式英语'],
  ['multilingual', 'Dylan', 'en_male_yangguangjieshuonan_uranus_bigtts', '通用场景, 视频配音,美式英语,多语种', '美式英语'],
  ['multilingual', 'Zendaya', 'en_female_zendaya_p1_uranus_bigtts', '教学场景, 客服场景,美式英语,多语种', '美式英语'],
  ['multilingual', 'Gracie', 'es_female_bv084_uranus_bigtts', '通用场景, 客服场景,多语种,西班牙语', '西班牙语'],
  ['multilingual', 'Dani', 'es_male_dani_uranus_bigtts', '有声阅读,视频配音,多语种,西班牙语', '西班牙语'],
  ['multilingual', 'Guillem', 'es_male_guillem_uranus_bigtts', '有声阅读,多语种,西班牙语', '西班牙语'],
  ['multilingual', 'Marisol', 'es_female_ht_mx_f6_uranus_bigtts', '通用场景, 视频配音,多语种,西班牙语', '西班牙语'],
  ['multilingual', 'Simone', 'fr_female_fr_bv078_uranus_bigtts', '通用场景, 视频配音,多语种,法语', '法语'],
  ['multilingual', 'Camille', 'fr_female_fr_f47_uranus_bigtts', '教学场景, 客服场景,多语种,法语', '法语'],
  ['multilingual', 'Maurice', 'fr_male_fr_m29_uranus_bigtts', '有声阅读,视频配音,多语种,法语', '法语'],
  ['multilingual', 'Rocco', 'id_male_bv160_uranus_bigtts', '通用场景, 视频配音,多语种,印尼语', '印尼语'],
  ['multilingual', 'Jude', 'id_male_bv160dialogue_uranus_bigtts', '通用场景, 视频配音,多语种,印尼语', '印尼语'],
  ['multilingual', 'Hugo', 'id_male_bv160narration_uranus_bigtts', '有声阅读,视频配音,多语种,印尼语', '印尼语'],
  ['multilingual', 'Clara', 'id_female_bv161_uranus_bigtts', '通用场景, 视频配音,多语种,印尼语', '印尼语'],
  ['multilingual', 'Sylvia', 'id_female_bv161dialogue_uranus_bigtts', '通用场景, 视频配音,多语种,印尼语', '印尼语'],
  ['multilingual', 'Celeste', 'id_female_bv161narration_uranus_bigtts', '通用场景, 视频配音,多语种,印尼语', '印尼语'],
  ['multilingual', 'Crew', 'id_female_bv164_uranus_bigtts', '通用场景, 视频配音,多语种,印尼语', '印尼语'],
  ['multilingual', 'Elian', 'id_male_bv164dialogue_uranus_bigtts', '视频配音,多语种,印尼语', '印尼语'],
  ['multilingual', 'Ronan', 'id_male_bv164narration_uranus_bigtts', '有声阅读,视频配音,多语种,印尼语', '印尼语'],
  ['multilingual', 'Chloe', 'id_female_f20_uranus_bigtts', '视频配音,多语种,印尼语', '印尼语'],
  ['multilingual', 'Han', 'id_male_han_uranus_bigtts', '通用场景,多语种,印尼语', '印尼语'],
  ['multilingual', 'Kyle', 'id_male_m08_uranus_bigtts', '通用场景, 教学场景,多语种,印尼语', '印尼语'],
  ['multilingual', 'Phulia', 'id_female_phulia_uranus_bigtts', '通用场景, 视频配音,多语种,印尼语', '印尼语'],
  ['multilingual', 'Bonnie', 'ja_female_bv024_uranus_bigtts', '通用场景, 教学场景,多语种,日语', '日语'],
  ['multilingual', 'Poppy', 'ja_female_bv520_uranus_bigtts', '视频配音, 角色扮演,多语种,日语', '日语'],
  ['multilingual', 'Aoi', 'ja_female_bv521_uranus_bigtts', '趣味口音, 角色扮演,多语种,日语', '日语'],
  ['multilingual', 'Hana', 'ja_female_bv522_uranus_bigtts', '通用场景, 教学场景, 客服场景,多语种,日语', '日语'],
  ['multilingual', 'Lily', 'ja_female_bv523_uranus_bigtts', '趣味口音, 角色扮演,多语种,日语', '日语'],
  ['multilingual', 'Ken', 'ja_male_bv524_uranus_bigtts', '通用场景, 视频配音,多语种,日语', '日语'],
  ['multilingual', 'Shirou', 'ja_female_shirou_uranus_bigtts', '视频配音, 角色扮演,多语种,日语', '日语'],
  ['multilingual', 'Jay', 'ko_male_bv545_uranus_bigtts', '通用场景, 视频配音,多语种,韩语', '韩语'],
  ['multilingual', 'Momo', 'ko_female_bv546_uranus_bigtts', '视频配音, 角色扮演,多语种,韩语', '韩语'],
  ['multilingual', 'Minho', 'ko_male_m03_uranus_bigtts', '通用场景, 客服场景,多语种,韩语', '韩语'],
  ['multilingual', 'Ham', 'ms_male_ham_uranus_bigtts', '通用场景, 教学场景,多语种,马来语', '马来语'],
  ['multilingual', 'Naim', 'ms_male_naim_uranus_bigtts', '通用场景, 客服场景,多语种,马来语', '马来语'],
  ['multilingual', 'Irene', 'mx_female_bv065_uranus_bigtts', '教学场景, 视频配音,多语种,墨西哥西语', '墨西哥西语'],
  ['multilingual', 'Diego', 'mx_male_bv165dialogue_uranus_bigtts', '有声阅读,视频配音,多语种,墨西哥西语', '墨西哥西语'],
  ['multilingual', 'Marcos', 'mx_male_bv165narrator_uranus_bigtts', '有声阅读,视频配音,多语种,墨西哥西语', '墨西哥西语'],
  ['multilingual', 'Lucy', 'mx_female_bv166dialogue_uranus_bigtts', '通用场景, 视频配音,多语种,墨西哥西语', '墨西哥西语'],
  ['multilingual', 'Rosa', 'mx_female_bv166emotion_uranus_bigtts', '通用场景, 视频配音,多语种,墨西哥西语', '墨西哥西语'],
  ['multilingual', 'Freya', 'mx_female_bv166narrator_uranus_bigtts', '有声阅读, 视频配音, 客服场景,多语种,墨西哥西语', '墨西哥西语'],
  ['multilingual', 'Derek', 'mx_male_ht_mx_m012_uranus_bigtts', '教学场景, 视频配音,多语种,墨西哥西语', '墨西哥西语'],
  ['multilingual', 'Leslie', 'mx_female_leslie_uranus_bigtts', '通用场景, 客服场景,多语种,墨西哥西语', '墨西哥西语'],
  ['multilingual', 'Marcelo', 'mx_male_marcelo_uranus_bigtts', '通用场景, 视频配音,多语种,墨西哥西语', '墨西哥西语'],
  ['multilingual', 'Sam', 'pt_male_bv172_uranus_bigtts', '通用场景, 客服场景,多语种,巴西葡萄牙语', '巴西葡萄牙语'],
  ['multilingual', 'Walter', 'pt_male_bv172dialogue_uranus_bigtts', '视频配音,多语种,巴西葡萄牙语', '巴西葡萄牙语'],
  ['multilingual', 'Vincent', 'pt_male_bv172emotion_uranus_bigtts', '教学场景, 视频配音,多语种,巴西葡萄牙语', '巴西葡萄牙语'],
  ['multilingual', 'Miles', 'pt_male_bv172narrator_uranus_bigtts', '有声阅读, 角色扮演,多语种,巴西葡萄牙语', '巴西葡萄牙语'],
  ['multilingual', 'Diana', 'pt_female_bv173_uranus_bigtts', '通用场景, 教学场景,多语种,巴西葡萄牙语', '巴西葡萄牙语'],
  ['multilingual', 'Elena', 'pt_female_bv173dialogue_uranus_bigtts', '视频配音, 客服场景,多语种,巴西葡萄牙语', '巴西葡萄牙语'],
  ['multilingual', 'Lola', 'pt_female_bv173emotion_uranus_bigtts', '通用场景, 教学场景,多语种,巴西葡萄牙语', '巴西葡萄牙语'],
  ['multilingual', 'Emma', 'pt_female_bv173narrator_uranus_bigtts', '视频配音, 客服场景,多语种,巴西葡萄牙语', '巴西葡萄牙语'],
  ['multilingual', 'Sofia', 'pt_female_bv530_uranus_bigtts', '通用场景, 视频配音,多语种,巴西葡萄牙语', '巴西葡萄牙语'],
  ['multilingual', 'Arthur', 'pt_male_bv531_uranus_bigtts', '通用场景, 教学场景,多语种,巴西葡萄牙语', '巴西葡萄牙语'],
  ['multilingual', 'Mari', 'pt_female_mari_uranus_bigtts', '教学场景, 视频配音,多语种,巴西葡萄牙语', '巴西葡萄牙语'],
  ['multilingual', 'Rael', 'pt_male_rael_uranus_bigtts', '教学场景, 视频配音,多语种,巴西葡萄牙语', '巴西葡萄牙语'],
  ['multilingual', 'Amelia', 'ru_female_af07_uranus_bigtts', '有声阅读,视频配音,多语种,俄语', '俄语'],
  ['multilingual', 'Irinae', 'ru_female_irinae_uranus_bigtts', '有声阅读,视频配音,多语种,俄语', '俄语'],
  ['multilingual', 'Pavel', 'ru_male_pavel_uranus_bigtts', '通用场景, 视频配音,多语种,俄语', '俄语'],
  ['multilingual', 'Ksenia', 'ru_female_sophie_uranus_bigtts', '通用场景,多语种,俄语', '俄语'],
  ['multilingual', 'Silas', 'ru_male_vlad_uranus_bigtts', '趣味口音,多语种,俄语', '俄语'],
  ['multilingual', 'Valeria', 'th_female_bv568_angry_uranus_bigtts', '教学场景, 视频配音,多语种,泰语', '泰语'],
  ['multilingual', 'Iris', 'th_female_bv568_fear_uranus_bigtts', '有声阅读,视频配音,多语种,泰语', '泰语'],
  ['multilingual', 'Zara', 'th_female_bv568_happy_uranus_bigtts', '通用场景, 视频配音,多语种,泰语', '泰语'],
  ['multilingual', 'Valentina', 'th_female_bv568_hate_uranus_bigtts', '通用场景, 视频配音,多语种,泰语', '泰语'],
  ['multilingual', 'Mildred', 'th_female_bv568_neutral_uranus_bigtts', '通用场景, 视频配音,多语种,泰语', '泰语'],
  ['multilingual', 'Lydia', 'th_female_bv568_sad_uranus_bigtts', '视频配音, 客服场景,多语种,泰语', '泰语'],
  ['multilingual', 'Phoebe', 'th_female_bv568_suprise_uranus_bigtts', '有声阅读,视频配音,多语种,泰语', '泰语'],
  ['multilingual', 'Annika', 'tl_female_annika_uranus_bigtts', '通用场景, 视频配音,多语种,菲律宾语', '菲律宾语'],
  ['multilingual', 'Ed', 'tl_male_ed_uranus_bigtts', '通用场景, 视频配音,多语种,菲律宾语', '菲律宾语'],
  ['multilingual', 'Hervie', 'tl_female_hervie_uranus_bigtts', '有声阅读, 视频配音, 客服场景,多语种,菲律宾语', '菲律宾语'],
  ['multilingual', 'Hong', 'vi_female_hong_uranus_bigtts', '通用场景, 客服场景,多语种,越南语', '越南语'],
  ['multilingual', 'Ling', 'vi_female_ling_uranus_bigtts', '通用场景, 视频配音,多语种,越南语', '越南语'],
  ['multilingual', 'Linh', 'vi_female_linh_uranus_bigtts', '视频配音,多语种,越南语', '越南语'],
  ['multilingual', 'Partner', 'vi_female_partner_uranus_bigtts', '视频配音, 客服场景,多语种,越南语', '越南语'],
  ['multilingual', 'Ruan', 'vi_female_ruan_uranus_bigtts', '通用场景,有声阅读, 角色扮演,多语种,越南语', '越南语'],
  ['multilingual', 'Wu', 'vi_female_wu_uranus_bigtts', '通用场景, 视频配音,多语种,越南语', '越南语'],
  ['multilingual', 'Wumg', 'vi_male_wumg_uranus_bigtts', '通用场景, 客服场景,多语种,越南语', '越南语'],
] as const satisfies readonly DoubaoOfficialVoiceRecord[]

/** Official Doubao Speech 2.0 voices supported by the bidirectional API. */
export const doubaoOfficialVoices: readonly DoubaoOfficialVoice[] = Object.freeze(
  officialVoiceRecords.map(([catalog, name, id, scene, languages]) => Object.freeze({
    catalog,
    id,
    languages,
    name,
    scene,
  })),
)

const officialVoicesById = new Map(doubaoOfficialVoices.map(voice => [voice.id, voice]))

/** Returns the official bidirectional voice for a voice_type value. */
export function findDoubaoOfficialVoice(id: string) {
  return officialVoicesById.get(id)
}

/** Returns true when a voice_type belongs to the official bidirectional list. */
export function isDoubaoOfficialVoice(id: string) {
  return officialVoicesById.has(id)
}
