<Project Sdk="Godot.NET.Sdk/4.7.1">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
    <Compile Include="../../../godot-kirie/packages/GdKirie.EventaAdapter/contentFiles/cs/any/GdKirie.EventaAdapter/KirieClientEventaBridge.cs" Link="KirieClientEventaBridge.cs" />
    <ProjectReference Include="../../../godot-kirie/packages/GdKirie.EventaAdapter/GdKirie.EventaAdapter.csproj" />
    <ProjectReference Include="../../../godot-kirie/packages/GdKirie.Platform/GdKirie.Platform.csproj" />
  </ItemGroup>

</Project>
