/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/caption': RouteRecordInfo<
      '/caption',
      '/caption',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chat': RouteRecordInfo<
      '/chat',
      '/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/': RouteRecordInfo<
      '/devtools/',
      '/devtools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/beat-sync': RouteRecordInfo<
      '/devtools/beat-sync',
      '/devtools/beat-sync',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/context-flow/': RouteRecordInfo<
      '/devtools/context-flow/',
      '/devtools/context-flow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/image': RouteRecordInfo<
      '/devtools/image',
      '/devtools/image',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/markdown-stress': RouteRecordInfo<
      '/devtools/markdown-stress',
      '/devtools/markdown-stress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/performance-visualizer': RouteRecordInfo<
      '/devtools/performance-visualizer',
      '/devtools/performance-visualizer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/plugin-host': RouteRecordInfo<
      '/devtools/plugin-host',
      '/devtools/plugin-host',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/providers-transcription-realtime-aliyun-nls': RouteRecordInfo<
      '/devtools/providers-transcription-realtime-aliyun-nls',
      '/devtools/providers-transcription-realtime-aliyun-nls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/screen-capture': RouteRecordInfo<
      '/devtools/screen-capture',
      '/devtools/screen-capture',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/use-electron-all-displays': RouteRecordInfo<
      '/devtools/use-electron-all-displays',
      '/devtools/use-electron-all-displays',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/use-electron-relative-mouse': RouteRecordInfo<
      '/devtools/use-electron-relative-mouse',
      '/devtools/use-electron-relative-mouse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/use-magic-keys': RouteRecordInfo<
      '/devtools/use-magic-keys',
      '/devtools/use-magic-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/use-window-mouse': RouteRecordInfo<
      '/devtools/use-window-mouse',
      '/devtools/use-window-mouse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/vibrant': RouteRecordInfo<
      '/devtools/vibrant',
      '/devtools/vibrant',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/websocket-inspector': RouteRecordInfo<
      '/devtools/websocket-inspector',
      '/devtools/websocket-inspector',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devtools/widgets-calling': RouteRecordInfo<
      '/devtools/widgets-calling',
      '/devtools/widgets-calling',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inlay/': RouteRecordInfo<
      '/inlay/',
      '/inlay',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notice/': RouteRecordInfo<
      '/notice/',
      '/notice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notice/fade-on-hover': RouteRecordInfo<
      '/notice/fade-on-hover',
      '/notice/fade-on-hover',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding': RouteRecordInfo<
      '/onboarding',
      '/onboarding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/airi-card/': RouteRecordInfo<
      '/settings/airi-card/',
      '/settings/airi-card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/connection/': RouteRecordInfo<
      '/settings/connection/',
      '/settings/connection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/connection/ConnectionSettings': RouteRecordInfo<
      '/settings/connection/ConnectionSettings',
      '/settings/connection/ConnectionSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/data/': RouteRecordInfo<
      '/settings/data/',
      '/settings/data',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/memory/': RouteRecordInfo<
      '/settings/memory/',
      '/settings/memory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/models/': RouteRecordInfo<
      '/settings/models/',
      '/settings/models',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/': RouteRecordInfo<
      '/settings/modules/',
      '/settings/modules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/beat-sync': RouteRecordInfo<
      '/settings/modules/beat-sync',
      '/settings/modules/beat-sync',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/consciousness': RouteRecordInfo<
      '/settings/modules/consciousness',
      '/settings/modules/consciousness',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/gaming-factorio': RouteRecordInfo<
      '/settings/modules/gaming-factorio',
      '/settings/modules/gaming-factorio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/gaming-minecraft': RouteRecordInfo<
      '/settings/modules/gaming-minecraft',
      '/settings/modules/gaming-minecraft',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/hearing': RouteRecordInfo<
      '/settings/modules/hearing',
      '/settings/modules/hearing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/mcp': RouteRecordInfo<
      '/settings/modules/mcp',
      '/settings/modules/mcp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/memory-long-term': RouteRecordInfo<
      '/settings/modules/memory-long-term',
      '/settings/modules/memory-long-term',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/memory-short-term': RouteRecordInfo<
      '/settings/modules/memory-short-term',
      '/settings/modules/memory-short-term',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/messaging-discord': RouteRecordInfo<
      '/settings/modules/messaging-discord',
      '/settings/modules/messaging-discord',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/messaging-qq': RouteRecordInfo<
      '/settings/modules/messaging-qq',
      '/settings/modules/messaging-qq',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/speech': RouteRecordInfo<
      '/settings/modules/speech',
      '/settings/modules/speech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/vision': RouteRecordInfo<
      '/settings/modules/vision',
      '/settings/modules/vision',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/modules/x': RouteRecordInfo<
      '/settings/modules/x',
      '/settings/modules/x',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/': RouteRecordInfo<
      '/settings/providers/',
      '/settings/providers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/chat/[providerId]': RouteRecordInfo<
      '/settings/providers/chat/[providerId]',
      '/settings/providers/chat/:providerId',
      { providerId: ParamValue<true> },
      { providerId: ParamValue<false> },
      | never
    >,
    '/settings/providers/chat/azure-ai-foundry': RouteRecordInfo<
      '/settings/providers/chat/azure-ai-foundry',
      '/settings/providers/chat/azure-ai-foundry',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/chat/cloudflare-workers-ai': RouteRecordInfo<
      '/settings/providers/chat/cloudflare-workers-ai',
      '/settings/providers/chat/cloudflare-workers-ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/chat/lm-studio': RouteRecordInfo<
      '/settings/providers/chat/lm-studio',
      '/settings/providers/chat/lm-studio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/chat/ollama': RouteRecordInfo<
      '/settings/providers/chat/ollama',
      '/settings/providers/chat/ollama',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/alibaba-cloud-model-studio': RouteRecordInfo<
      '/settings/providers/speech/alibaba-cloud-model-studio',
      '/settings/providers/speech/alibaba-cloud-model-studio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/comet-api-speech': RouteRecordInfo<
      '/settings/providers/speech/comet-api-speech',
      '/settings/providers/speech/comet-api-speech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/deepgram-tts': RouteRecordInfo<
      '/settings/providers/speech/deepgram-tts',
      '/settings/providers/speech/deepgram-tts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/elevenlabs': RouteRecordInfo<
      '/settings/providers/speech/elevenlabs',
      '/settings/providers/speech/elevenlabs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/index-tts-vllm': RouteRecordInfo<
      '/settings/providers/speech/index-tts-vllm',
      '/settings/providers/speech/index-tts-vllm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/kokoro-local': RouteRecordInfo<
      '/settings/providers/speech/kokoro-local',
      '/settings/providers/speech/kokoro-local',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/microsoft-speech': RouteRecordInfo<
      '/settings/providers/speech/microsoft-speech',
      '/settings/providers/speech/microsoft-speech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/openai-audio-speech': RouteRecordInfo<
      '/settings/providers/speech/openai-audio-speech',
      '/settings/providers/speech/openai-audio-speech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/openai-compatible-audio-speech': RouteRecordInfo<
      '/settings/providers/speech/openai-compatible-audio-speech',
      '/settings/providers/speech/openai-compatible-audio-speech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/player2-speech': RouteRecordInfo<
      '/settings/providers/speech/player2-speech',
      '/settings/providers/speech/player2-speech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/speech/volcengine': RouteRecordInfo<
      '/settings/providers/speech/volcengine',
      '/settings/providers/speech/volcengine',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/transcription/aliyun-nls-transcription': RouteRecordInfo<
      '/settings/providers/transcription/aliyun-nls-transcription',
      '/settings/providers/transcription/aliyun-nls-transcription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/transcription/browser-web-speech-api': RouteRecordInfo<
      '/settings/providers/transcription/browser-web-speech-api',
      '/settings/providers/transcription/browser-web-speech-api',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/transcription/comet-api-transcription': RouteRecordInfo<
      '/settings/providers/transcription/comet-api-transcription',
      '/settings/providers/transcription/comet-api-transcription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/transcription/openai-audio-transcription': RouteRecordInfo<
      '/settings/providers/transcription/openai-audio-transcription',
      '/settings/providers/transcription/openai-audio-transcription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/transcription/openai-compatible-audio-transcription': RouteRecordInfo<
      '/settings/providers/transcription/openai-compatible-audio-transcription',
      '/settings/providers/transcription/openai-compatible-audio-transcription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/scene/': RouteRecordInfo<
      '/settings/scene/',
      '/settings/scene',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/system/': RouteRecordInfo<
      '/settings/system/',
      '/settings/system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/system/color-scheme': RouteRecordInfo<
      '/settings/system/color-scheme',
      '/settings/system/color-scheme',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/system/developer': RouteRecordInfo<
      '/settings/system/developer',
      '/settings/system/developer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/system/general': RouteRecordInfo<
      '/settings/system/general',
      '/settings/system/general',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/system/window-shortcuts': RouteRecordInfo<
      '/settings/system/window-shortcuts',
      '/settings/system/window-shortcuts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/v2/': RouteRecordInfo<
      '/v2/',
      '/v2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/v2/settings': RouteRecordInfo<
      '/v2/settings',
      '/v2/settings',
      Record<never, never>,
      Record<never, never>,
      | '/v2/settings/'
      | '/v2/settings/providers'
      | '/v2/settings/providers/'
      | '/v2/settings/providers/edit'
      | '/v2/settings/providers/edit/[providerId]/'
    >,
    '/v2/settings/': RouteRecordInfo<
      '/v2/settings/',
      '/v2/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/v2/settings/providers': RouteRecordInfo<
      '/v2/settings/providers',
      '/v2/settings/providers',
      Record<never, never>,
      Record<never, never>,
      | '/v2/settings/providers/'
      | '/v2/settings/providers/edit'
      | '/v2/settings/providers/edit/[providerId]/'
    >,
    '/v2/settings/providers/': RouteRecordInfo<
      '/v2/settings/providers/',
      '/v2/settings/providers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/v2/settings/providers/edit': RouteRecordInfo<
      '/v2/settings/providers/edit',
      '/v2/settings/providers/edit',
      Record<never, never>,
      Record<never, never>,
      | '/v2/settings/providers/edit/[providerId]/'
    >,
    '/v2/settings/providers/edit/[providerId]/': RouteRecordInfo<
      '/v2/settings/providers/edit/[providerId]/',
      '/v2/settings/providers/edit/:providerId',
      { providerId: ParamValue<true> },
      { providerId: ParamValue<false> },
      | never
    >,
    '/widgets': RouteRecordInfo<
      '/widgets',
      '/widgets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/renderer/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/renderer/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/renderer/pages/caption.vue': {
      routes:
        | '/caption'
      views:
        | never
    }
    'src/renderer/pages/chat.vue': {
      routes:
        | '/chat'
      views:
        | never
    }
    'src/renderer/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/renderer/pages/devtools/index.vue': {
      routes:
        | '/devtools/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/beat-sync.vue': {
      routes:
        | '/devtools/beat-sync'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/context-flow/index.vue': {
      routes:
        | '/devtools/context-flow/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/image.vue': {
      routes:
        | '/devtools/image'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/markdown-stress.vue': {
      routes:
        | '/devtools/markdown-stress'
      views:
        | never
    }
    'src/renderer/pages/devtools/performance-visualizer.vue': {
      routes:
        | '/devtools/performance-visualizer'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/plugin-host.vue': {
      routes:
        | '/devtools/plugin-host'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/providers-transcription-realtime-aliyun-nls.vue': {
      routes:
        | '/devtools/providers-transcription-realtime-aliyun-nls'
      views:
        | never
    }
    'src/renderer/pages/devtools/screen-capture.vue': {
      routes:
        | '/devtools/screen-capture'
      views:
        | never
    }
    'src/renderer/pages/devtools/use-electron-all-displays.vue': {
      routes:
        | '/devtools/use-electron-all-displays'
      views:
        | never
    }
    'src/renderer/pages/devtools/use-electron-relative-mouse.vue': {
      routes:
        | '/devtools/use-electron-relative-mouse'
      views:
        | never
    }
    'src/renderer/pages/devtools/use-magic-keys.vue': {
      routes:
        | '/devtools/use-magic-keys'
      views:
        | never
    }
    'src/renderer/pages/devtools/use-window-mouse.vue': {
      routes:
        | '/devtools/use-window-mouse'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/vibrant.vue': {
      routes:
        | '/devtools/vibrant'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/devtools/websocket-inspector.vue': {
      routes:
        | '/devtools/websocket-inspector'
      views:
        | never
    }
    'src/renderer/pages/devtools/widgets-calling.vue': {
      routes:
        | '/devtools/widgets-calling'
      views:
        | never
    }
    'src/renderer/pages/inlay/index.vue': {
      routes:
        | '/inlay/'
      views:
        | never
    }
    'src/renderer/pages/notice/index.vue': {
      routes:
        | '/notice/'
      views:
        | never
    }
    'src/renderer/pages/notice/fade-on-hover.vue': {
      routes:
        | '/notice/fade-on-hover'
      views:
        | never
    }
    'src/renderer/pages/onboarding.vue': {
      routes:
        | '/onboarding'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/airi-card/index.vue': {
      routes:
        | '/settings/airi-card/'
      views:
        | never
    }
    'src/renderer/pages/settings/connection/index.vue': {
      routes:
        | '/settings/connection/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/connection/ConnectionSettings.vue': {
      routes:
        | '/settings/connection/ConnectionSettings'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/data/index.vue': {
      routes:
        | '/settings/data/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/memory/index.vue': {
      routes:
        | '/settings/memory/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/models/index.vue': {
      routes:
        | '/settings/models/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/index.vue': {
      routes:
        | '/settings/modules/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/beat-sync.vue': {
      routes:
        | '/settings/modules/beat-sync'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/consciousness.vue': {
      routes:
        | '/settings/modules/consciousness'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/gaming-factorio.vue': {
      routes:
        | '/settings/modules/gaming-factorio'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/gaming-minecraft.vue': {
      routes:
        | '/settings/modules/gaming-minecraft'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/hearing.vue': {
      routes:
        | '/settings/modules/hearing'
      views:
        | never
    }
    'src/renderer/pages/settings/modules/mcp.vue': {
      routes:
        | '/settings/modules/mcp'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/memory-long-term.vue': {
      routes:
        | '/settings/modules/memory-long-term'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/memory-short-term.vue': {
      routes:
        | '/settings/modules/memory-short-term'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/messaging-discord.vue': {
      routes:
        | '/settings/modules/messaging-discord'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/messaging-qq.vue': {
      routes:
        | '/settings/modules/messaging-qq'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/speech.vue': {
      routes:
        | '/settings/modules/speech'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/vision.vue': {
      routes:
        | '/settings/modules/vision'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/modules/x.vue': {
      routes:
        | '/settings/modules/x'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/index.vue': {
      routes:
        | '/settings/providers/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/chat/[providerId].vue': {
      routes:
        | '/settings/providers/chat/[providerId]'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/chat/azure-ai-foundry.vue': {
      routes:
        | '/settings/providers/chat/azure-ai-foundry'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/chat/cloudflare-workers-ai.vue': {
      routes:
        | '/settings/providers/chat/cloudflare-workers-ai'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/chat/lm-studio.vue': {
      routes:
        | '/settings/providers/chat/lm-studio'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/chat/ollama.vue': {
      routes:
        | '/settings/providers/chat/ollama'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/alibaba-cloud-model-studio.vue': {
      routes:
        | '/settings/providers/speech/alibaba-cloud-model-studio'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/comet-api-speech.vue': {
      routes:
        | '/settings/providers/speech/comet-api-speech'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/deepgram-tts.vue': {
      routes:
        | '/settings/providers/speech/deepgram-tts'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/elevenlabs.vue': {
      routes:
        | '/settings/providers/speech/elevenlabs'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/index-tts-vllm.vue': {
      routes:
        | '/settings/providers/speech/index-tts-vllm'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/kokoro-local.vue': {
      routes:
        | '/settings/providers/speech/kokoro-local'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/microsoft-speech.vue': {
      routes:
        | '/settings/providers/speech/microsoft-speech'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/openai-audio-speech.vue': {
      routes:
        | '/settings/providers/speech/openai-audio-speech'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/openai-compatible-audio-speech.vue': {
      routes:
        | '/settings/providers/speech/openai-compatible-audio-speech'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/player2-speech.vue': {
      routes:
        | '/settings/providers/speech/player2-speech'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/speech/volcengine.vue': {
      routes:
        | '/settings/providers/speech/volcengine'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/transcription/aliyun-nls-transcription.vue': {
      routes:
        | '/settings/providers/transcription/aliyun-nls-transcription'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/transcription/browser-web-speech-api.vue': {
      routes:
        | '/settings/providers/transcription/browser-web-speech-api'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/transcription/comet-api-transcription.vue': {
      routes:
        | '/settings/providers/transcription/comet-api-transcription'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/transcription/openai-audio-transcription.vue': {
      routes:
        | '/settings/providers/transcription/openai-audio-transcription'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/providers/transcription/openai-compatible-audio-transcription.vue': {
      routes:
        | '/settings/providers/transcription/openai-compatible-audio-transcription'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/scene/index.vue': {
      routes:
        | '/settings/scene/'
      views:
        | never
    }
    'src/renderer/pages/settings/system/index.vue': {
      routes:
        | '/settings/system/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/settings/system/color-scheme.vue': {
      routes:
        | '/settings/system/color-scheme'
      views:
        | never
    }
    'src/renderer/pages/settings/system/developer.vue': {
      routes:
        | '/settings/system/developer'
      views:
        | never
    }
    'src/renderer/pages/settings/system/general.vue': {
      routes:
        | '/settings/system/general'
      views:
        | never
    }
    'src/renderer/pages/settings/system/window-shortcuts.vue': {
      routes:
        | '/settings/system/window-shortcuts'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/v2/index.vue': {
      routes:
        | '/v2/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/v2/settings.vue': {
      routes:
        | '/v2/settings'
        | '/v2/settings/'
        | '/v2/settings/providers'
        | '/v2/settings/providers/'
        | '/v2/settings/providers/edit'
        | '/v2/settings/providers/edit/[providerId]/'
      views:
        | 'default'
    }
    '../../packages/stage-pages/src/pages/v2/settings/index.vue': {
      routes:
        | '/v2/settings/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/v2/settings/providers.vue': {
      routes:
        | '/v2/settings/providers'
        | '/v2/settings/providers/'
        | '/v2/settings/providers/edit'
        | '/v2/settings/providers/edit/[providerId]/'
      views:
        | 'default'
    }
    '../../packages/stage-pages/src/pages/v2/settings/providers/index.vue': {
      routes:
        | '/v2/settings/providers/'
      views:
        | never
    }
    '../../packages/stage-pages/src/pages/v2/settings/providers/edit.vue': {
      routes:
        | '/v2/settings/providers/edit'
        | '/v2/settings/providers/edit/[providerId]/'
      views:
        | 'default'
    }
    '../../packages/stage-pages/src/pages/v2/settings/providers/edit/[providerId]/index.vue': {
      routes:
        | '/v2/settings/providers/edit/[providerId]/'
      views:
        | never
    }
    'src/renderer/pages/widgets.vue': {
      routes:
        | '/widgets'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
