using System;
using System.IO;
using Godot;

/// <summary>
/// Imports materialized VRM files into detached Godot scene nodes.
///
/// Use when:
/// - Electron main has written the selected VRM bytes to a native file path.
/// - Godot needs to create a runtime avatar node from that file.
///
/// Expects:
/// - The vendored VRM add-on exists under <c>res://addons/vrm</c>.
/// - <c>res://scripts/vrm/VrmRuntimeImporter.gd</c> mirrors the add-on's runtime import path.
///
/// Returns:
/// - A detached <see cref="Node"/> generated by Godot's GLTF runtime importer.
///
/// Call stack:
///
/// StageSceneController.Apply
///   -> <see cref="Load"/>
///     -> VrmRuntimeImporter.gd.import_vrm
///       -> res://addons/vrm/vrm_extension.gd
/// </summary>
public sealed class VrmAvatarLoader
{
    private const string ImporterScriptPath = "res://scripts/vrm/VrmRuntimeImporter.gd";

    private static readonly StringName ImportVrmMethod = new("import_vrm");
    private static readonly StringName GetLastErrorMethod = new("get_last_error");

    /// <summary>
    /// Loads a materialized VRM file into a detached Godot node.
    ///
    /// Use when:
    /// - Scene input has already passed the G1.1 VRM-only format gate.
    ///
    /// Expects:
    /// - <paramref name="payload"/> contains a native absolute file path readable by the Godot process.
    ///
    /// Returns:
    /// - A node ready to be added to the active scene tree.
    /// </summary>
    public Node Load(StageSceneApplyPayload payload)
    {
        if (string.IsNullOrWhiteSpace(payload.Path))
        {
            throw new InvalidOperationException("VRM file path was empty.");
        }

        // Electron materializes selected models under app userData, outside Godot's res:// tree.
        // System.IO checks the native absolute path before the GDScript importer hands it to GLTFDocument.
        if (!File.Exists(payload.Path))
        {
            throw new FileNotFoundException("VRM file does not exist.", payload.Path);
        }

        using var importer = CreateImporter();
        var importedObject = importer.Call(ImportVrmMethod, payload.Path).AsGodotObject();
        if (importedObject is Node importedNode)
        {
            return importedNode;
        }

        var importerError = importer.Call(GetLastErrorMethod).AsString();
        if (string.IsNullOrWhiteSpace(importerError))
        {
            importerError = "VRM importer returned an empty scene.";
        }

        throw new InvalidOperationException(importerError);
    }

    private static GodotObject CreateImporter()
    {
        var script = ResourceLoader.Load<GDScript>(ImporterScriptPath);
        if (script == null)
        {
            throw new InvalidOperationException($"Failed to load VRM runtime importer script: {ImporterScriptPath}.");
        }

        var importer = script.New().AsGodotObject();
        if (importer == null)
        {
            throw new InvalidOperationException("Failed to create VRM runtime importer.");
        }

        return importer;
    }
}
