import type { ContextUpdate } from '@proj-airi/server-sdk'
import type { Tool } from '@xsai/shared-chat'

import type { SparkNotifyRuntimeEvent } from './types'

import { errorMessageFrom } from '@moeru/std'
import { rawTool } from '@xsai/tool'
import { toJsonSchema, validate } from 'xsschema'
import { z } from 'zod'

import { normalizeNullableAnyOf, sparkNotifyCommandSchema } from './schema'

/**
 * Tool registration options for the spark-notify runtime.
 */
export interface CreateSparkNotifyToolsOptions {
  /** Enables or disables registration of the `builtIn_sparkNoResponse` tool. */
  allowNoResponse?: boolean
  /** Enables or disables registration of the `builtIn_sparkCommand` tool. */
  allowSparkCommand?: boolean
  /** Receives validated command drafts emitted by `builtIn_sparkCommand`. */
  onCommands: (commands: SparkNotifyCommandDraft[]) => void
  /** Receives runtime events from tool calls and tool execution. */
  onEvent?: (event: SparkNotifyRuntimeEvent) => void
  /** Receives the no-response signal emitted by `builtIn_sparkNoResponse`. */
  onNoResponse: () => void
}

/**
 * Normalized `builtIn_sparkCommand` payload forwarded to downstream orchestrators.
 */
export interface SparkNotifyCommandDraft {
  /** Optional acknowledgement text that may be surfaced by the downstream consumer. */
  ack?: string
  /** Optional context patches that should accompany the emitted command. */
  contexts?: ContextUpdate<Record<string, unknown>, undefined>[]
  /** Target agent or lane identifiers that should receive the emitted command. */
  destinations: string[]
  /** Optional structured guidance generated by the notify agent for the downstream command target. */
  guidance?: {
    /** Candidate options the downstream agent may choose from while executing the command. */
    options: Array<{
      /** Optional fallback steps the downstream agent may use if the option fails. */
      fallback?: string[]
      /** Human-readable label for the candidate option. */
      label: string
      /** Optional possible outcomes the downstream agent should anticipate. */
      possibleOutcome?: string[]
      /** Optional rationale explaining why this option is suggested. */
      rationale?: string
      /** Optional qualitative risk level for the option. */
      risk?: 'high' | 'low' | 'medium' | 'none'
      /** Ordered steps the downstream agent should follow for the option. */
      steps: string[]
      /** Optional trigger cues indicating when the option should be selected. */
      triggers?: string[]
    }>
    /** Trait-strength map that hints at which persona qualities the downstream agent should favor. */
    persona?: Record<string, 'high' | 'low' | 'medium' | 'very-high' | 'very-low'>
    /** Guidance mode describing how the downstream agent should interpret the options. */
    type: 'instruction' | 'memory-recall' | 'proposal'
  }
  /** Optional intent describing why the downstream agent should process the command. */
  intent?: 'action' | 'context' | 'pause' | 'plan' | 'proposal' | 'reroute' | 'resume'
  /** Optional interrupt mode used by downstream schedulers. */
  interrupt?: 'force' | 'soft' | boolean
  /** Optional command priority used by downstream schedulers. */
  priority?: 'critical' | 'high' | 'low' | 'normal'
}

/**
 * Creates built-in tools used by the Spark Notify agent.
 *
 * Use when:
 * - Running the Spark Notify agent on any runtime (web, desktop, eval harness)
 * - You need "no response" and "command draft" tool pathways
 *
 * Expects:
 * - Callbacks for command collection and no-response signaling
 *
 * Returns:
 * - Tool array consumable by `@xsai/stream-text`
 */
export async function createSparkNotifyTools(options: CreateSparkNotifyToolsOptions) {
  const allowNoResponse = options.allowNoResponse !== false
  const allowSparkCommand = options.allowSparkCommand !== false

  const tools: Tool[] = []

  if (allowNoResponse) {
    const name = 'builtIn_sparkNoResponse'

    tools.push(rawTool({
      description: 'Indicate that no response or action is needed for the current spark:notify event.',
      execute: async (_rawPayload, context) => {
        options.onEvent?.({ payload: { toolCallId: context?.toolCallId, toolName: name }, type: 'model-output-tool-call' })
        options.onNoResponse()
        options.onEvent?.({ payload: { responseMode: 'no-response', toolCallId: context?.toolCallId, toolName: name }, type: 'tool-execution' })

        return 'AIRI System: Acknowledged, no response or action will be processed.'
      },
      name: 'builtIn_sparkNoResponse',
      parameters: normalizeNullableAnyOf(await toJsonSchema(z.object({}).strict()) as any),
    }))
  }

  if (allowSparkCommand) {
    const name = 'builtIn_sparkCommand'

    tools.push(rawTool({
      description: 'Issue a spark:command to sub-agents. You can call this tool multiple times.',
      execute: async (rawPayload, context) => {
        options.onEvent?.({ payload: { rawPayload, toolCallId: context?.toolCallId, toolName: name }, type: 'model-output-tool-call' })

        try {
          const payload = rawPayload as z.infer<typeof sparkNotifyCommandSchema>
          const validated = await validate(sparkNotifyCommandSchema, payload)

          options.onCommands(validated.commands.map(normalizeSparkNotifyCommand))
          options.onEvent?.({ payload: { commandCount: validated.commands.length, toolCallId: context?.toolCallId, toolName: name }, type: 'tool-execution' })
        }
        catch (error) {
          options.onEvent?.({ payload: { error: errorMessageFrom(error), ok: false, toolCallId: context?.toolCallId, toolName: name }, type: 'tool-execution' })
          return `AIRI System: Error - invalid spark_command parameters: ${errorMessageFrom(error)}`
        }

        return 'AIRI System: Acknowledged, command fired.'
      },
      name,
      parameters: normalizeNullableAnyOf(await toJsonSchema(sparkNotifyCommandSchema) as any),
    }))
  }

  return { tools }
}

/**
 * Normalizes provider-facing notify command payloads into websocket draft commands.
 *
 * Use when:
 * - LLM output has been validated against `sparkNotifyCommandSchema`
 * - You need `spark:command`-compatible draft objects
 *
 * Expects:
 * - Input shape from one `commands[]` entry
 *
 * Returns:
 * - Runtime-ready command draft for downstream emitters
 */
function normalizeSparkNotifyCommand(
  command: z.infer<typeof sparkNotifyCommandSchema>['commands'][number],
): SparkNotifyCommandDraft {
  return {
    ack: command.ack || undefined,
    // TODO: contexts can be added later
    contexts: [],
    destinations: command.destinations,
    guidance: command.guidance
      ? {
          options: command.guidance.options.map(option => ({
            ...option,
            fallback: option.fallback?.length ? option.fallback : undefined,
            possibleOutcome: option.possibleOutcome?.length ? option.possibleOutcome : undefined,
            rationale: option.rationale ?? undefined,
            risk: option.risk ?? undefined,
            triggers: option.triggers?.length ? option.triggers : undefined,
          })),
          persona: command.guidance.persona?.reduce((acc, curr) => {
            acc[curr.traits] = curr.strength
            return acc
          }, {} as Record<string, 'high' | 'low' | 'medium' | 'very-high' | 'very-low'>) || undefined,
          type: command.guidance.type,
        }
      : undefined,
    intent: command.intent || 'action',
    interrupt: command.interrupt === 'false' || command.interrupt == null ? false : command.interrupt,
    priority: command.priority || 'normal',
  }
}
