name: damage-taken
version: 1

trigger:
  modality: felt
  kind: damage_taken

accumulator:
  threshold: 1
  window: 500ms

signal:
  type: saliency_high
  description: 'Taken damage!'
  confidence: 1.0
  metadata:
    action: damage
