import type { ServerManager } from '../../../http-server/server-manager/types'
import type { StaticAssetManifestEntry } from '../../../http-server/static-assets'
import type { StaticAssetSession } from '../../../http-server/static-assets/types'

import { createStaticAssetService } from '../../../http-server/static-assets'
import { buildMountedStaticAssetPath } from '../../../http-server/static-assets/paths'

/**
 * Describes the cookie material Electron must apply before loading an extension asset URL.
 *
 * Use when:
 * - Main process bridges server-side asset sessions into Electron's cookie jar
 * - Revocation needs enough cookie identity to remove previously issued asset cookies
 *
 * Expects:
 * - `url` belongs to the local asset server origin
 * - `path` matches the server-issued cookie path for the asset session route
 *
 * Returns:
 * - N/A
 */
export interface ExtensionAssetCookie {
  /** Unix timestamp in milliseconds when the cookie-backed asset session expires. */
  expiresAt: number
  /** Cookie name generated for the asset session. */
  name: string
  /** Route path scope generated by the asset session store. */
  path: string
  /** Absolute URL on the local asset server used by Electron cookie APIs. */
  url: string
  /** Opaque cookie value required by the static asset route. */
  value: string
}

/**
 * Applies and removes extension asset cookies from the Electron host.
 *
 * Use when:
 * - Asset sessions must exist in Electron's cookie jar before an iframe navigates to its URL
 * - Asset session revocation must remove browser-visible cookie state
 *
 * Expects:
 * - `setCookie` resolves only after Electron can send the cookie for matching asset URLs
 * - `removeCookie` is idempotent for already-removed cookies
 *
 * Returns:
 * - N/A
 */
export interface ExtensionAssetCookieAdapter {
  removeCookie: (cookie: ExtensionAssetCookie) => Promise<void>
  setCookie: (cookie: ExtensionAssetCookie) => Promise<void>
}

/**
 * Defines the extension-owned asset hosting service used by the extension host.
 *
 * Use when:
 * - Plugin snapshots need mounted asset URLs without depending on the H3 server shape
 * - Host teardown must revoke extension asset access independently from widget/gamelet logic
 *
 * Expects:
 * - Implementations own the underlying transport, cookie, and session lifecycle
 *
 * Returns:
 * - A startable/stoppable asset-hosting service with generic extension-facing methods
 */
export interface ExtensionAssetService extends ServerManager {
  createAssetSession: (input: ExtensionAssetSessionInput) => Promise<ExtensionAssetSession>
  getBaseUrl: () => string | undefined
  revokeAll: () => Promise<void>
  revokeByExtensionId: (extensionId: string) => Promise<void>
  revokeByOwnerSessionId: (ownerSessionId: string) => Promise<void>
  revokeSession: (assetSessionId: string) => Promise<void>
}

/**
 * Describes an extension asset session prepared for renderer iframe navigation.
 *
 * Use when:
 * - A plugin iframe needs a mounted static asset URL and pre-applied cookie state
 * - Callers need the opaque session id for later targeted revocation
 *
 * Expects:
 * - `cookie` was set through the host adapter before the value is returned
 *
 * Returns:
 * - Renderer-facing URL plus server and cookie metadata
 */
export interface ExtensionAssetSession {
  /** Opaque server-side asset session id embedded in mounted asset routes. */
  assetSessionId: string
  /** Cookie data that was applied through the host adapter. */
  cookie: ExtensionAssetCookie
  /** Unix timestamp in milliseconds when the cookie-backed asset session expires. */
  expiresAt: number
  /** Absolute mounted asset URL safe to hand to a renderer iframe after cookie setup. */
  url: string
}

/**
 * Describes one extension asset session creation request.
 *
 * Use when:
 * - An extension-owned asset URL must be mounted behind the local loopback server with cookie auth
 * - Snapshot builders need a transport-agnostic way to authorize one extension asset route before iframe load
 *
 * Expects:
 * - `extensionId` matches a manifest entry registered in the asset host
 * - `routeAssetPath` identifies the iframe entry asset relative to the mounted `/ui` route
 * - `pathPrefix` is scoped to the mounted route prefix accepted by the session store
 *
 * Returns:
 * - N/A
 */
export interface ExtensionAssetSessionInput {
  /** Extension manifest id that owns the static asset root. */
  extensionId: string
  /** Parent extension session id used for owner-scoped revocation. */
  ownerSessionId: string
  /** Allowed asset path prefix enforced by the server-side session store. */
  pathPrefix: string
  /** Asset path to mount in the returned renderer-facing URL. */
  routeAssetPath: string
  /** Session lifetime in milliseconds from creation or refresh time. */
  ttlMs: number
  /** Extension/plugin version expected by the server-side session validator. */
  version: string
}

/**
 * Describes the extension asset methods needed while building renderer-facing snapshots.
 *
 * Use when:
 * - Snapshot builders must request route-scoped asset sessions without depending on HTTP server internals
 * - Host bootstrap wants to layer caching or policy on top of the raw asset transport
 *
 * Expects:
 * - `routeAssetPath` identifies the mounted asset file being exposed in the snapshot
 * - Implementations set host cookies before returning renderer-facing URLs
 *
 * Returns:
 * - A mounted asset URL and cookie-backed session metadata
 */
export interface ExtensionAssetSnapshotService {
  createAssetSession: (input: Omit<ExtensionAssetSessionInput, 'ttlMs'>) => Promise<ExtensionAssetSession>
  getBaseUrl: () => string | undefined
}

/**
 * Creates the extension asset host service backed by the extension static asset server.
 *
 * Use when:
 * - The extension host needs to expose mounted asset URLs to renderer snapshots
 * - Asset session lifecycle should stay inside the extension domain instead of the HTTP server layer
 *
 * Expects:
 * - `getManifestEntryByExtensionId` returns the latest extension root/version map
 * - `cookieAdapter` writes and removes cookies in the Electron host session used by plugin iframes
 *
 * Returns:
 * - An extension-facing asset host service with generic extension asset methods
 */
export function createExtensionAssetService(options: {
  cookieAdapter: ExtensionAssetCookieAdapter
  getManifestEntryByExtensionId: () => Map<string, StaticAssetManifestEntry>
}): ExtensionAssetService {
  const server = createStaticAssetService({ getManifestEntryByExtensionId: options.getManifestEntryByExtensionId })
  let lastBaseUrl: string | undefined

  const readBaseUrl = () => {
    const baseUrl = server.getBaseUrl()
    lastBaseUrl = baseUrl ?? lastBaseUrl
    return baseUrl
  }

  const revokeSessions = async (sessions: readonly StaticAssetSession[]) => {
    const baseUrl = readBaseUrl() ?? lastBaseUrl
    if (!baseUrl) {
      return
    }

    await Promise.all(
      sessions.map(session => options.cookieAdapter.removeCookie(createExtensionAssetCookie(baseUrl, session))),
    )
  }

  return {
    async createAssetSession(input) {
      const session = server.createSession({
        extensionId: input.extensionId,
        ownerSessionId: input.ownerSessionId,
        pathPrefix: input.pathPrefix,
        ttlMs: input.ttlMs,
        version: input.version,
      })

      try {
        const baseUrl = readBaseUrl()
        if (!baseUrl) {
          throw new Error('Extension asset server base URL is unavailable; start the asset server before creating asset sessions')
        }

        const mountedPath = buildMountedStaticAssetPath({
          assetPath: input.routeAssetPath,
          assetSessionId: session.assetSessionId,
          extensionId: input.extensionId,
        })

        if (!mountedPath) {
          throw new RangeError('Extension asset session routeAssetPath must be a safe extension asset path')
        }

        const cookie = createExtensionAssetCookie(baseUrl, session)
        await options.cookieAdapter.setCookie(cookie)

        return {
          assetSessionId: session.assetSessionId,
          cookie,
          expiresAt: session.expiresAt,
          url: new URL(mountedPath, baseUrl).toString(),
        }
      }
      catch (error) {
        server.revokeSession(session.assetSessionId)
        throw error
      }
    },
    getBaseUrl() {
      return readBaseUrl()
    },
    key: 'extension-assets',
    async revokeAll() {
      await revokeSessions(server.revokeAll())
    },
    async revokeByExtensionId(extensionId) {
      await revokeSessions(server.revokeByExtensionId(extensionId))
    },
    async revokeByOwnerSessionId(ownerSessionId) {
      await revokeSessions(server.revokeByOwnerSessionId(ownerSessionId))
    },
    async revokeSession(assetSessionId) {
      const session = server.revokeSession(assetSessionId)
      if (!session) {
        return
      }

      await revokeSessions([session])
    },
    async start() {
      await server.start()
    },
    async stop() {
      await revokeSessions(server.revokeAll())
      await server.stop()
    },
  }
}

function createExtensionAssetCookie(baseUrl: string, session: StaticAssetSession): ExtensionAssetCookie {
  return {
    expiresAt: session.expiresAt,
    name: session.cookieName,
    path: session.cookiePath,
    url: new URL(session.cookiePath, baseUrl).toString(),
    value: session.cookieValue,
  }
}
