#!/usr/bin/env tsx
/**
 * gen-pnpm-packages.ts — Generate layered Nix derivations from pnpm-lock.yaml.
 *
 * Run with: pnpm run nix:gen
 *
 * Generates:
 *   nix/pnpm-packages.nix  — one fetchurl per package (~2990 entries)
 *   nix/pnpm-store.nix     — per-package CAFS assembly + merge derivation
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { parse as parseYaml } from 'yaml'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(__dirname, '..', '..')
const nixDir = join(repoRoot, 'nix')

// ---------------------------------------------------------------------------
// Parse pnpm-lock.yaml
// ---------------------------------------------------------------------------

interface PnpmPackageEntry {
  resolution: {
    integrity: string
    tarball?: string // only present for non-registry packages
  }
  engines?: Record<string, string>
  hasBin?: boolean
  cpu?: string[]
  os?: string[]
  libc?: string[]
  deprecated?: string
  bundled?: boolean
}

interface PnpmLockfile {
  lockfileVersion: string
  packages?: Record<string, PnpmPackageEntry>
}

const lockfilePath = join(repoRoot, 'pnpm-lock.yaml')
console.log('Reading pnpm-lock.yaml...')
const lockfileContent = readFileSync(lockfilePath, 'utf-8')
const lockfile = parseYaml(lockfileContent) as PnpmLockfile

if (!lockfile.packages || Object.keys(lockfile.packages).length === 0) {
  console.error('No packages found in pnpm-lock.yaml')
  process.exit(1)
}

// ---------------------------------------------------------------------------
// Extract packages
// ---------------------------------------------------------------------------

interface Package {
  /** e.g. "vue@3.4.0" or "@vue/core@3.4.0" */
  key: string
  /** npm package name, possibly scoped */
  name: string
  version: string
  /** sha512-<base64> integrity of the tarball */
  integrity: string
  /** tarball download URL */
  url: string
}

/**
 * Compute the npm registry tarball URL from a package name and version.
 * Scoped packages: @scope/name → registry.npmjs.org/@scope/name/-/name-version.tgz
 * Unscoped: name → registry.npmjs.org/name/-/name-version.tgz
 */
function npmTarballUrl(name: string, version: string): string {
  const unscopedName = name.includes('/') ? name.split('/')[1] : name
  return `https://registry.npmjs.org/${name}/-/${unscopedName}-${version}.tgz`
}

const packages: Package[] = []

for (const [key, entry] of Object.entries(lockfile.packages)) {
  // Skip bundled dependencies (no tarball to download)
  if (entry.bundled) {
    continue
  }

  // Parse "name@version" — last @ is the separator (handles @scope/name@version)
  const lastAt = key.lastIndexOf('@')
  const name = key.slice(0, lastAt)
  const version = key.slice(lastAt + 1)

  const integrity = entry.resolution?.integrity
  if (!integrity) {
    console.warn(`Skipping ${key}: no integrity hash`)
    continue
  }
  if (!integrity.startsWith('sha512-')) {
    console.warn(`Skipping ${key}: unsupported integrity format ${integrity.split('-')[0]}`)
    continue
  }

  // Use explicit tarball URL if present (e.g. GitHub packages, private registry)
  const url = entry.resolution?.tarball ?? npmTarballUrl(name, version)

  packages.push({ key, name, version, integrity, url })
}

packages.sort((a, b) => a.key.localeCompare(b.key))
console.log(`Found ${packages.length} packages`)

// ---------------------------------------------------------------------------
// Escape a string for use inside a Nix string literal (double-quoted)
// ---------------------------------------------------------------------------
function nixStr(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$\{/g, '\\${')
}

// ---------------------------------------------------------------------------
// Generate nix/pnpm-packages.nix
// ---------------------------------------------------------------------------

function generatePnpmPackagesNix(pkgs: Package[]): string {
  const lines: string[] = [
    '# AUTO-GENERATED by nix/scripts/gen-pnpm-packages.ts — DO NOT EDIT',
    '# Run: pnpm run nix:gen',
    '{ fetchurl }:',
    '# Each entry is { drv = <fetchurl derivation>; integrity = "sha512-..."; }',
    '# pnpm-store.nix uses drv for the tarball path and integrity for the CAFS index path.',
    '{',
  ]

  for (const pkg of pkgs) {
    lines.push(`  "${nixStr(pkg.key)}" = {`)
    lines.push(`    drv = fetchurl {`)
    lines.push(`      url = "${nixStr(pkg.url)}";`)
    lines.push(`      hash = "${nixStr(pkg.integrity)}";`)
    lines.push(`    };`)
    lines.push(`    integrity = "${nixStr(pkg.integrity)}";`)
    lines.push(`  };`)
  }

  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Generate nix/pnpm-store.nix
// ---------------------------------------------------------------------------

function generatePnpmStoreNix(pkgs: Package[]): string {
  const lines: string[] = [
    '# AUTO-GENERATED by nix/scripts/gen-pnpm-packages.ts — DO NOT EDIT',
    '# Run: pnpm run nix:gen',
    '{',
    '  stdenvNoCC,',
    '  lib,',
    '  fetchurl,',
    '  nodejs,',
    '  pnpm,',
    '}:',
    'let',
    '  # Use import (not callPackage) to avoid callPackage injecting `override` into',
    '  # the attrset, which would cause lib.mapAttrs to iterate over it as a package.',
    '  packages = import ./pnpm-packages.nix { inherit fetchurl; };',
    '',
    '  # Each package gets its own derivation: extract tarball → write CAFS fragment.',
    '  # This derivation is independently cached by Nix — only re-runs when its',
    '  # tarball input changes (i.e. when that specific package is updated).',
    '  # pkg = { drv = <fetchurl>; integrity = "sha512-..."; }',
    '  makePkgStore = key: pkg:',
    '    stdenvNoCC.mkDerivation {',
    '      name = "airi-pnpm-pkg-${lib.replaceStrings [ "@" "/" ] [ "" "-" ] key}";',
    '      nativeBuildInputs = [ nodejs ];',
    '      buildPhase = \'\'',
    '        node ${./scripts/cafs-add.mjs} \\',
    '          "${pkg.drv}" \\',
    '          "$out" \\',
    '          "${key}" \\',
    '          "${pkg.integrity}"',
    '      \'\';',
    '      dontConfigure = true;',
    '      dontUnpack = true;',
    '      dontInstall = true;',
    '      dontFixup = true;',
    '    };',
    '',
    `  # ${pkgs.length} independent store fragments — one per package`,
    '  pkgStores = lib.mapAttrs makePkgStore packages;',
    '',
    'in',
    '# Merge all per-package CAFS fragments into one complete pnpm store.',
    '# CAFS is content-addressed: cp -rn is safe (same hash = same file, no conflicts).',
    '#',
    '# NOTICE: pkgStoresList is passed via passAsFile instead of being interpolated',
    '# directly into buildPhase. With ~3000 packages each path is ~50 chars, the',
    '# concatenated string exceeds ARG_MAX (~2 MB) when bash is invoked with all',
    '# environment variables, causing E2BIG. passAsFile writes the content to a',
    '# temp file and sets pkgStoresListPath, keeping the env small. Nix still',
    '# tracks the string context (i.e. dependencies on all pkgStores) correctly.',
    '#',
    '# NOTICE: pnpm is added as a nativeBuildInput solely to detect the CAFS store',
    '# version subdirectory (e.g. "v10") at merge build time via `pnpm store path`.',
    '# This avoids hardcoding the version and automatically adapts when nixpkgs',
    '# updates pnpm to a version that bumps its internal store layout. The per-package',
    '# builds (makePkgStore) do NOT include pnpm, so their drv hashes are unaffected',
    '# by pnpm version bumps — only this single merge derivation reruns.',
    '# Fix: trailing newline in pkgStoresList - 2026-04-07',
    'stdenvNoCC.mkDerivation {',
    '  name = "airi-pnpm-deps";',
    '  nativeBuildInputs = [ pnpm ];',
    '  passAsFile = [ "pkgStoresList" ];',
    '  pkgStoresList = (lib.concatStringsSep "\\n" (lib.attrValues pkgStores)) + "\\n";',
    '  buildPhase = \'\'',
    '    # Detect pnpm\'s internal CAFS version subdirectory (e.g. "v10").',
    '    # pnpm appends this as the last segment of its store path.',
    '    export HOME=$(mktemp -d)',
    '    # Suppress packageManager version mismatch errors (we\'re not in a project dir)',
    '    pnpm config set manage-package-manager-versions false 2>/dev/null || true',
    '    storeVer=$(basename "$(pnpm store path 2>/dev/null)")',
    '    # Validate: must be v<digits>; fall back to v10 if detection fails',
    '    [[ "$storeVer" =~ ^v[0-9]+$ ]] || storeVer=v10',
    '',
    '    mkdir -p "$out/$storeVer/files" "$out/$storeVer/index"',
    '    while IFS= read -r store; do',
    '      [ -z "$store" ] && continue',
    '      if [ -d "$store/files" ]; then',
    '        # NOTICE: --no-preserve=mode prevents cp from copying Nix store directory',
    '        # permissions (0555, read-only) into $out. Without it, the first package',
    '        # to create e.g. files/cd/ sets it to 0555, and subsequent packages fail',
    '        # to write into it with "Permission denied".',
    '        cp -rn --no-preserve=mode "$store/files/." "$out/$storeVer/files/"',
    '      fi',
    '      if [ -d "$store/index" ]; then',
    '        cp -rn --no-preserve=mode "$store/index/." "$out/$storeVer/index/"',
    '      fi',
    '    done < "$pkgStoresListPath"',
    '    # NOTICE: CAFS v10 files with -exec suffix denote executable binaries (e.g. turbo, esbuild).',
    '    # Set their permissions to 555 (r-xr-xr-x) so pnpm can execute them during install.',
    '    # Without this, pnpm install fails with EACCES when trying to run native binaries.',
    '    find "$out" -type f -name "*-exec" -print0 | xargs -0 chmod 555',
    '    # fetcherVersion=2 tells pnpmConfigHook the store is a raw directory (not a tarball)',
    '    echo -n "2" > "$out/.fetcher-version"',
    '  \'\';',
    '  dontConfigure = true;',
    '  dontUnpack = true;',
    '  dontInstall = true;',
    '  dontFixup = true;',
    '}',
    '',
  ]

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Write output files
// ---------------------------------------------------------------------------

const pnpmPackagesNix = join(nixDir, 'pnpm-packages.nix')
const pnpmStoreNix = join(nixDir, 'pnpm-store.nix')

console.log('Generating nix/pnpm-packages.nix...')
writeFileSync(pnpmPackagesNix, generatePnpmPackagesNix(packages))

console.log('Generating nix/pnpm-store.nix...')
writeFileSync(pnpmStoreNix, generatePnpmStoreNix(packages))

console.log(`Done. Generated ${packages.length} package derivations.`)
console.log('  nix/pnpm-packages.nix')
console.log('  nix/pnpm-store.nix')
console.log('')
console.log('Next: commit these files, then run: nix build .#airi.pnpmDeps')
