[build]
publish = "packages/memory-driver-duckdb/playground/dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
