/**
 * Auto-generated plugin metadata
 * This file is generated by vite-plugin-plugins-metadata
 * DO NOT EDIT MANUALLY
 */

import type { PluginMetadata } from './plugins'

export const KNOWN_PLUGINS: Record<string, PluginMetadata> = {
  'bilibili-laplace': {
    id: 'bilibili-laplace',
    name: 'settings.pages.plugins.known.bilibili-laplace.title',
    description: 'settings.pages.plugins.known.bilibili-laplace.description',
    icon: 'i-simple-icons:bilibili',
    iconColor: 'text-pink-500',
  },
  'claude-code': {
    id: 'claude-code',
    name: 'manifest.json description',
    description: 'manifest.json description',
    icon: 'i-simple-icons:anthropic',
    iconColor: 'text-orange-500',
  },
  'homeassistant': {
    id: 'homeassistant',
    name: 'settings.pages.plugins.known.homeassistant.title',
    description: 'settings.pages.plugins.known.homeassistant.description',
    icon: 'i-simple-icons:homeassistant',
    iconColor: 'text-cyan-500',
  },
  'vscode': {
    id: 'vscode',
    name: 'AIRI',
    description: 'VSCode extension that shares your coding context with AIRI',
    icon: 'i-simple-icons:visualstudiocode',
    iconColor: 'text-blue-500',
  },
  'web-extension': {
    id: 'web-extension',
    name: 'manifest.json description',
    description: 'manifest.json description',
    icon: 'i-simple-icons:googlechrome',
    iconColor: 'text-blue-400',
  },
}
