name: Deploy to HuggingFace Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy-moonshine-web-vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - run: |-
          git clone https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/moeru-ai/moonshine-web-vue --depth 1 packages/moonshine-web/dist
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}

      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install
      - run: pnpm build

      - name: Push to hub
        working-directory: ./packages/moonshine-web/dist
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |-
          mv ../README.md .
          git add .
          git config --local user.email "neko@ayaka.moe"
          git config --local user.name "Neko Ayaka"
          git commit -m "release: build ${{ github.sha }}"
          git push -f
