name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 26.7.0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.2

      - name: Configure npm registry
        uses: actions/setup-node@v6
        with:
          # registry-url required. Learn more at
          # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
          registry-url: 'https://registry.npmjs.org'

      # npm 11.5.1 or later is required so update to latest to use OIDC trusted publisher
      # https://github.com/eslint/config-inspector/pull/174/files
      # https://github.com/e18e/ecosystem-issues/issues/201
      - run: npm install -g npm@latest

      - name: Cache bun dependencies
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - run: bun install --frozen-lockfile
      - run: bun run build:packages

      - run: bun run publish:packages -- --dry-run

      - run: bun run publish:packages
